### ISSUE TITLE
Loading-Strategy-Testbed identification

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#1]
In order to test and improve the S-101 loading strategy, we will need both test datasets and visualization tools able to load and display ENCs like an ECDIS.
Please inform you you are able to provide S-101 test datasets or if you have a vizualisation tool.

**Comment by DavidGrant-NIWC** [comment]
The NIWC test bed ShoreECDIS app is intended to demonstrate ECDIS visualization along with the ability to meet other ECDIS requirements. The following caveats apply:

* **All** dataset features are loaded if any dataCoverage meets the display conditions spelled out in the PS.
  * It is not clear how features (really the spatial(s) associated with each feature) should be assigned to individual data coverages.
  * The PS is essentially saying that each dataCoverage should be treated as an individual dataset, but the data model does not fully support this concept.
  * Rather then implementing the display requirements as written, the ShoreECDIS clips each feature during rendering:
    * The clip region is comprised of the containing datasets data coverage footprints which meet the loading/unloading criteria spelled out in the PS.
    * Implementing in this manner allows features such as light sector leg lines and sector arcs to be visible across multiple data coverages / datasets.
* Due to the lack of supporting data the loading / unloading implementation has not been tested in the case where a dataset contains multiple data coverages of differing scale.

![image](https://user-images.githubusercontent.com/62906211/118515635-8ccd9400-b703-11eb-98df-b0b33497e48a.png)

**Comment by DavidGrant-NIWC** [comment]
The latest NIWC test bed is available from: [Basecamp S-100 Test Bed files](https://basecamp.com/2933368/projects/9982931/attachments)
_Contact Julia Powell for access to Basecamp_

The test bed will also be made available from the IHO registry in the Help&Guidance/Repository section: [IHO registry](http://registry.iho.int/repository/list.do)

**Comment by DavidGrant-NIWC** [comment]
The developmental S-101 portrayal catalogue is available from: [S-101 portrayal catalogue (unofficial)](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/releases)

A compatible S-101 feature catalogue is provided in the download.

**Comment by alvarosanuy** [comment]
[101AU00411142.zip](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/6621405/101AU00411142.zip)

This ENC has been converted from S-57 using the latest ESRI converter with no additional changes. It does contain a number of different DataCoverages. I tried to load it in NIWC's SENC Editor 1.1.0.0 but it reports an Error. Maybe it needs some 'massaging' using an S-101 Editor beforehand ....
Hope it helps

**Comment by DavidGrant-NIWC** [comment]
> [101AU00411142.zip](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/6621405/101AU00411142.zip)
> 
> This ENC has been converted from S-57 using the latest ESRI converter with no additional changes. It does contain a number of different DataCoverages. I tried to load it in NIWC's SENC Editor 1.1.0.0 but it reports an Error. Maybe it needs some 'massaging' using an S-101 Editor beforehand ....
> Hope it helps

Issues with the dataset:
* It has four occurances of TidalStreamPanelData.referenceTide = "0", which is invalid and causes the dataset to fail validation. Valid values are:
![image](https://user-images.githubusercontent.com/62906211/121376563-a41d2d00-c90f-11eb-9d79-fab1758ac13b.png)
* It has six DataCoverage features. This is technically not allowed (S-101 says a max of three), but the testbed does support it.
* It has a DataCoverage feature with minDisplayScale and maxDisplayScale both set to 90,000. This is also technically not an error, but the dataset will only load when the display scale is set to exactly 1:90,000
* The DataCoverage referenced in the previous bullet has an invalid geometry:
![image](https://user-images.githubusercontent.com/62906211/121380303-c19fc600-c912-11eb-95ef-e56800997246.png)

**Comment by alvarosanuy** [comment]
S-101 Ed 1.0.1 does not limit the number of data Coverage features to any particular number. That was amended in Ed 1.0.0 and this clause should only be reviewed if testing develops a very strong case against this practice..

**Refer to 2.5.1:**
An ENC dataset can contain more than one Data Coverage (see clause 3.4).’
**and 3.4:**
‘..that excessive use of multiple Data Coverage features having different values of maximum display scale within a single dataset should be avoided.’

I think that this dataset can be very good for testing the loading/unloading principles. Maybe Christian can use Caris to fix what the SENC reader does not like and then use this ENC for testing in the shore-ECDIS.

**Comment by DavidGrant-NIWC** [comment]
Edited my previous comment - agree that S-101 ed 1.0 does not limit the number of data coverage features.

**Comment by JeffWootton** [comment]
No comment on this GitHub issue since June 2021. Consider that this may have been overtaken by events (S-101PT discussions, publication of S-101 Edition 1.1.0. Issue closed bending any further requirement.
