### ISSUE TITLE
Implementation of optimumDisplayScale

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#101]
In accordance with Action S-101PT11-21, the attribute optimumDisplayScale has been re-introduced in S-101 for implementation and testing prior to the development of the first operational Edition 2.0.0. Comments regarding the implementation and testing of the amended scale regime to include optimumDisplayScale doe S-101 Edition 1.2.0 are welcome. 

A comment regarding this change has been included in the closed Issue #87, and is as follows:

@benhazelgrove: After multiple discussions internally at AHO, we believe that MaxDS should be a value that is equal to compilation scale of data. Allowing the Mariner to zoom past the intended viewing scale without an overscale pattern is not what our products were developed for. The error of positioning is multiplied, and it's not something we are comfortable with allowing.
If any example of this was to be used in our case, we would only see a use case for the largest scale product in our portfolio. (Port cell for example)

Using both MaxDs and OptimumDS is not required for our portfolio. We envisage that we will populate MaxDS (matching S-57 comp scale) and MinDS (matching the next smaller scale product MaxDS in our gridded scheme). AHO can use this approach as we have used the attribute SCAMIN to identify features and display them at a scale where we believe they should appear. Our overlapping S-57 products have consistent SCAMIN values for corresponding features in each product.

This discussion leads to the loading/display issues we are seeing, where MinDS is used to display a DataCoverage until +1, whereas we would like it to use MinDS -1.

**Comment by alvarosanuy** [comment]
@JeffWootton  - Just to clarify Ben's comments, **we do not need ODS** to achieve what we need. We are happy for the Overscale pattern to be triggered at 2 x MaxDS as per S-52 rules when MaxDS=CSCL.
The introduction of MinDS allows us to 'close' the gap' between datasets when zooming out (we'll ensure mariners do not shift from not being over scaled to suddenly being over scaled when a smaller scale products is loaded!).
The only scenario when overscale would kick in is when the loaded product is the largest scale available in the area and the mariner decides to continue zooming in. In this only case, we are happy for the Overscale Indication (factor) and pattern to behave as per S-52. **We do not need ODS**.
Furthermore, we find the idea of ENC producers setting different (and maybe variable) MaxDs values using their own criteria and triggering a different over scale behavior than S-52 (particularly during DF period), **unrealistic and probably not recommended**. 
I wouldn't like to deal with an accident investigation where I have to explain why a mariner did not get Overscale warnings in S-57 but they would have if they were using S-101 (or the other way around).

**Comment by DavidGrant-NIWC** [comment]
> We are happy for the Overscale pattern to be triggered at 2 x MaxDS as per S-52 rules when MaxDS=CSCL.

S-52 rules display the pattern at 2x CSCL. The encoding you will be using (MaxDS=CSCL) will display the pattern at 1x CSCL. The pattern will be displayed on your charts when the error is half as much as the equivalent S-52 chart.

There are cases where the pattern will not be displayed regardless of the MSVS/MaxDS/CSCL:
* When the display is "intentionally overscaled".
* When the pattern is turned off (via viewing group `21030` or VGL `Chart scale boundaries`).

**Comment by JeffWootton** [comment]
This Issue is to be discussed at the S-101PT12 second session on 07 March 2024. Some initial "food for thought" to promote discussion:
- Suggest that, regardless of the outcome of the discussions, the attribute defining the "compilation scale" of the data is retained as "optimum display scale" rather than reverting back to "maximum display scale" as it was in S-101 Edition 1.1.0. This will then align the term with the definition of "compilation scale" as it is in the S-57 UOC at clause 2.2.6, which is "_The compilation scale should be considered as the optimum display scale of ENC data._".
- The term "maximum display scale" would then remain as the term applying to the scale at which the gross overscale indication (prison bars) is activated as the mariner zooms in beyond the optimum display scale. The only question then remaining, I think, is whether the maximum display scale should be encoded in the data (as an attribute as currently in S-101 Edition 1.2.0) or managed within the ECDIS as is currently done with S-52.

The above is intended, in part, to try to reduce as much as possible the changes required to S-101 documentation, regardless of the decision taken over the application of the concepts.

**Comment by MikusRL** [comment]
Could another possible solution be to automatically create the MaxDS value during the conversion process or when creating new product by the production software based on the S-52 2x rule? So the CSCl woud be converted to OptimumDS, and the value for the MaxDS would be calculated and added automatically based on the OptimumDS, and then, if needed, it can be edited by the producer as per their policies or needs. 

By the way, what is the correct abbreviation of OptimumDS - same as Max and Min? E.g. - MinDS, OptDS and MaxDS?

**Comment by MikusRL** [comment]
It could be actually that this discussion earlier is in a way in support to Optimum display scale use now, as this finds that MaxDs is not fulfilling a role for compilation scale...
https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/17

**Comment by JeffWootton** [comment]
S-101PT13 agreed to the retention of `optimumDisplayScale` for S-101 Edition 2.0.0.

Close issue pending testing, including full testing using a full portfolio of ENCs of data load and rendering in ECDIS as transferred to the S-98 Sub-Group.
