### ISSUE TITLE
Encoding of mangrove

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#102]
In S-101, area mangrove will be encoded by an **Obstruction** with category of obstruction = 23.
1.2.0 DCEG (§13.6.1.1) states that:
"_Where the source indicates that a mangrove area is in the intertidal area, an **Obstruction** feature of type area, with attribute **category of obstruction** = 23 (mangrove) should be encoded on top of the portion of the intertidal area..._"
Does that mean that it will still be allowed to encode area mangrove on a **Land Area** (as it is in S-57)? This would mean having an **Obstruction** on **Land Area**???
As mangrove is always situated in intertidal areas, shouldn't we mandate the encoding in S-101.
The wording could be:
"_As mangroves are always situated in intertidal areas, an **Obstruction** feature of type area, with attribute **category of obstruction** = 23 (mangrove) must be encoded on top of the portion of the intertidal area..._"
The question then is to know if the converters: will be able to automatically cut the S-57 **LNDARE** to create appropriate **Depth Area** in S-101? This would avoid fastidious manual editing for data providers.

**Comment by JeffWootton** [comment]
The current modelling end encoding guidance allows for the generalization of mangrove areas (encoding the seaward edge of the mangrove as `Coastline` bordering `LandArea`) on smaller scale ENCs. This is allowable in accordance with S-4.

For ENC conversion where mangrove has been encoded over intertidal area in accordance with the S-57 work-around, the mangrove `VEGATN` area will convert to mangrove `Obstruction` and the "apparent" S-57 `COALNE` along the seaward edge will be deleted. For the generalized mangrove encoding instances as described above, the conversion will be 1 to 1.

Suggest that no change is required.

**Comment by JeffWootton** [comment]
S-101PT13 Decision: No further action required.

Close Issue.
