### ISSUE TITLE
Discontinue 'Display Uncertainties' Boolean attribute

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S-101-Documentation-and-FC#103]
The PsWG decided not to allocate dedicated portrayal instructions to the horizontal and/or vertical uncertainties encoded in hydrographic features in depths =< 30m.
It was noted that 'display uncertainties' was introduced without mariner's input and that, based on initial testing, it will severely impact the legibility of ENC data.
Accordingly, mariners won't be allowed to graphically visualize feature's Uncertainties (turn them ON/OFF) at their will. The recommendation is to **only use** Vertical & Horizontal uncertainties to trigger A&I (at mariners' request). Both, during route planning and route monitoring phases.

The PsWG is open to re-asses this topic in the future if a mariner supported Use Case is submitted to the S101PT for consideration.

Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/1#issuecomment-1771906264

Accordingly, it is recommended that the Boolean attribute **displayUncertainties** and associated encoding guidance are removed from the S-101 FC and DCEG.

**Comment by JeffWootton** [comment]
Based on some of the correspondence I have seen over the past few weeks regarding IMO requirements for display of encoded feature uncertainties during route planning and monitoring, I agree with this recommendation from the Portrayal Sub-Working Group.

**Comment by alvarosanuy** [comment]
**Can we make this decision at S101PT12?**

**Comment by TomRichardson6** [comment]
I think that the work from the ENCWG on uncertainties has effectively superseded this. I would like to make a decision at PT12 but I wonder if we need to go ahead here and simply report this decision at PT13.

**Comment by JeffWootton** [comment]
S-101PT12 Decision: Apply changes throughout as recommended in paper S-101PT12-05.1.1 (for S-101 Edition 1.3.0 draft).

Changes applied 07 march 2024. Close issue.
