### ISSUE TITLE
Figures needing update

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-101-Documentation-and-FC#105]
DCEG

1. Figure 2-1 – Spatial Quality information type (to conform to new modeling of Spatial Quality in 24.5)

**Comment by rmalyankar** [comment]
@JeffWootton Too busy next week or two but expect to have time after that

**Comment by JeffWootton** [comment]
Figure updated 27 March 2024 (for Edition 1.3.0).

Close Issue.
