### ISSUE TITLE
 S-101 exhibition of light = fog light is not allowed for a Light Sectored

### ISSUE THREAD

**Issue by RichardCoyles** [iho-ohi/S-101-Documentation-and-FC#107]
Some GB cells have LIGHTS which have visible sectors defined and has EXCLIT = Fog Light. 
On conversion to S-101 this value is not allowed so we are losing the fact that this is a Fog Light.
Is there a reason why S-101 exhibition of light = fog light is not allowed for a Light Sectored? 
We would like it to be considered for inclusion in the DGEG so those light sectors captured as fog light in these cases will convert. 

Can any other member states find examples like those below?

Example from GB50202N below, there are 3 examples of this encoding in S-57 on this cell.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/108347351/1bef813a-3cb1-4519-92b8-81f76e495707)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/108347351/431aedb6-4564-458c-b870-35011843f4cf)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/108347351/d92e6410-ef3d-4166-bf82-087c41517a73)

**Comment by forodd** [comment]
I just queried our lights db and out of 22.600 LIGHT objects, none of them have EXCLIT=3, so Norway has no experience on this. That beeing said, I don't remember any reason for leaving it out for S-101, so support it beeing added unless there are valid reasons not to add it..

**Comment by Christian-Shom** [comment]
We have 7 lights in our database with EXCLIT=3 and SECTR1/SECTR2 encoded.
I haven't asked our specialists here (I can do it if needed) if these are not mistakes, but would tend to agree that exhibition of light = fog light should be allowed for a Light Sectored.

**Comment by JeffWootton** [comment]
I have not been able to find a reason why exhibitionConditionOfLight = 3 in any of the records of the DCEG Sub-Group. There appear to be use cases presented for inclusion for S-101 Edition 2.0.0, so have therefore added exhibitionConditionOfLight = 3 as an allowable value for the feature LightSectored. For consideration at S-101PT12.

Close Issue pending approval at S-101PT12.
