### ISSUE TITLE
DCEG 1.2 references `display name` rather than `name usage`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#109]
`display name` was replaced by `name usage`. Clause 2.4.5 still references `display name`.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/0130cf40-d0ac-40d7-a758-dff57935f935)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/1fa8b56d-2919-422c-a323-b5124d68168d)

**Comment by JeffWootton** [comment]
Has been corrected for draft Edition 2.0.0. Display name at DCEG clause 2.4.5 has been replaces with name usage as follows:

**name usage** – this sub-attribute determines the priority and level of display (full display or Pick Report only) where multiple instance of the complex attribute feature name are encoded for a single feature instance, based on Mariner’s selected ECDIS display settings (see clause 2.5.8).

To be confirmed at S-101PT12 - then close Issue.

**Comment by JeffWootton** [comment]
Approved at S-101Pt12. Close Issue.
