### ISSUE TITLE
FC 1.2 has invalid multiplicity for `categoryOfDolphin`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#110]
Should be 1,1:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/5fab19fa-e9af-414a-9803-b55fb5a67936)

FC 1.2 binds with infinite="true" and value of "1". Not sure if there is a schematron check for this (binding with both a value and infinite="true"), but there should be.
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/4e8de87b-0abb-4a63-b23f-4ad174d05d98)

**Comment by TomRichardson6** [comment]
KHOA is now preparing an updated FC which will address this change, Issue to be closed once this version is available.

**Comment by kusala9** [comment]
> KHOA is now preparing an updated FC which will address this change, Issue to be closed once this version is available.

"and tested successfully" 😄 ... I'll do a couple of samples for the other issue of the duplicate association groups and post them here. Might help guide the efforts too.

**Comment by JeffWootton** [comment]
S-101PT12: This Issue has been resolved for FC Edition 1.2.1.

Close Issue.
