### ISSUE TITLE
Add attribute reportedDate to feature LandArea

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#111]
Comment from NL during review of draft Edition 1.2.0 of S-65 Annex A (S-57 ENC to S-101 Conversion Guidance):

UOC:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/537268ad-4691-4dea-9c4f-7e91d9da5ea2)

DCEG:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/09cc99d6-3141-4e9e-aea2-8cd54b70b3a8)

Land Area does not have the attribute reported date in S-101. SORDAT information on LNDAREA feature will be lost in conversion.

------------------------------------------------------------

The recommendation from the ENC Conversion Sub-Group is that, in order to allow the encoding of information regarding (reclamation) works in progress, the attribute reportedDate is added as an allowable attribute for the feature LandArea. This will also ensure that information regarding works in progress or projected will not be lost during teh S-57 to S-101 conversion process.

**Comment by TomRichardson6** [comment]
Support adding this attribute. Surprised it wasn't there already.

**Comment by JeffWootton** [comment]
Proposal approved at S-101PT12. Close Issue.
