### ISSUE TITLE
10100AA_STNDR.000 ed3 `DistanceMark`'s have unknown attributes

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#112]
At least one feature should have populated attributes so that the text label is visible.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/bc1eadb6-ffc9-4f14-bb81-873fc7545dd6)

**Comment by kusala9** [comment]
did you mean to raise this in the S-164 subgroup? I have added attribution to the distance marks and refreshed in the repository. Suggest this is closed and re-raised if neccessary. Not sure if the values are meaningful....

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/ebcbd043-60d9-48f8-9340-51fef87cb947)
