### ISSUE TITLE
Allowable vales of waterLevelEffect for LandRegion

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#116]
Comment from UK: Attribute **water level effect** currently only has values _1_ or _6_ for feature **Land Region**, however some of the values for **category of land region** may, by definition, be in the intertidal area.

IHO Sec Response:  Comment is specific to marsh - by definition, marsh is "An area of wet, often spongy ground that is subject to frequent flooding or tidal inundations, but not considered to be continually under water. ...".  This to me is water level effect = _6_. Therefore consider that no further action is required.

Other opinions are welcome on this issue.

**Comment by alvarosanuy** [comment]
Tend to agree with Jeff's comments.

**Comment by Richard-Fowle** [comment]
DK agrees with Jeff's comments

**Comment by JeffWootton** [comment]
S-101PT12 Decision: There is no requirement to amend the allowable values for waterLevelEffect on LandRegion.

Close Issue.
