### ISSUE TITLE
Add inTheWater as an allowable attribute for feature BuiltUpArea

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#118]
Consideration should be given to amending the encoding of built-up areas over water to be similar as for buildings, landmarks, etc.  That is, adding the "system" attribute **in the water** and amending the encoding guidance accordingly.

**SHOM:**  Quite agree with Editor Comments. Encoding of Coast Line should be suppressed.

**Comment by alvarosanuy** [comment]
Supported

**Comment by Richard-Fowle** [comment]
Supported

**Comment by JeffWootton** [comment]
S-101PT12 Decision: It was approved to add inTheWater as an allowable attribute for the feature BuiltUpArea.

Applied to S-101 DCEG with accompanying guidance 08 March 2024.

Close Issue.
