### ISSUE TITLE
CableOverhead - allowable value for attribute categoryOfCable

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#119]
Suggest that values _4_ (telephone) and _5_ (telegraph) for attribute **category of cable** are replaced with new value _10_ (telecommunications cable) for feature **Overhead Cable**.

**Comment by alvarosanuy** [comment]
Supported. I believe this was already done for submarine cables.

**Comment by Richard-Fowle** [comment]
Supported
