### ISSUE TITLE
`PylonBridgeSupport` attribute `featureName`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#122]
Why does `PylonBridgeSupport` bind `featureName`?

`SpanFixed` and `SpanOpening` don't bind `featureName`, and the name of the `Bridge` is intended to be shown relative to the (required) spatial attribute associated with the `Bridge` feature. Is there a desire to label individual pylons?

**Comment by DavidGrant-NIWC** [comment]
I think I see that this is to label pylons which aren't part of bridges. Might want to note that in the DCEG (but maybe it's obvious to everyone except me). Go ahead and close this issue if desired.

**Comment by JeffWootton** [comment]
I recall a discussion on this a few years ago, noting that OBJNAM/NOBJNM are allowable attributes for PYLONS in S-57. The use case was put forward that some bridges have the pylons named or numbered and the port regulations/guidance includes information regarding which pylons to navigate between dependent on direction of passage, vessel size/class, etc.

Suggest that this issue can be closed with no further action.
