### ISSUE TITLE
Why does `Sounding` have `featureName` attribute?

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#124]
* If this is not an error, how is this supposed to be portrayed? Should each point be labeled?
* If `featureName` is removed then the binding to `TextPlacement` should also be removed.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/f96850be-9148-4c2c-99f5-aa4a10861cb4)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/a6352f8d-e0bd-43c0-b04c-a004f97bd66f)

**Comment by JeffWootton** [comment]
This is nor an error. The complex attribute featureName is required on soundings to encode the name for a feature such as an isolated shoal.

Regarding "Should each point be labeled?": Within the current model, soundings can only be included in a group if all the feature attributes for the soundings are identical. Therefore a single isolated sounding having featureName populated cannot be included in a sounding group.

**Comment by DavidGrant-NIWC** [comment]
Ok, I will see if we can label the first point in the multipoint associated with the sounding feature. You may want to add a note in the DCEG that the name will only be displayed on the first sounding, or that if name is encoded there should only be a single point in the associated spatial.

**Comment by JeffWootton** [comment]
I have added the following new draft Remarks bullet at clause 11.3.1:

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/6db7fd8a-31c5-4901-8836-af22e83b15e4)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/972f7ca1-ab5b-4460-b884-58fb259f8649)
