### ISSUE TITLE
fixedDateRange upper multiplicity not consistent with other features for Bollard.

### ISSUE THREAD

**Issue by tdepuyt** [iho-ohi/S-101-Documentation-and-FC#125]
S-101 1.2.0 FC shows 
			<S100FC:attributeBinding sequential="false">
				<S100FC:multiplicity>
					<S100Base:lower>0</S100Base:lower>
					<S100Base:upper>1</S100Base:upper>
				</S100FC:multiplicity>
				<S100FC:attribute ref="fixedDateRange"/>
			</S100FC:attributeBinding>

Should be

			<S100FC:attributeBinding sequential="false">
				<S100FC:multiplicity>
					<S100Base:lower>0</S100Base:lower>
					<S100Base:upper xsi:nil="false" infinite="false">1</S100Base:upper>
				</S100FC:multiplicity>
				<S100FC:attribute ref="fixedDateRange"/>
			</S100FC:attributeBinding>

A

**Comment by TomRichardson6** [comment]
KHOA is now preparing an updated FC which will address this change, Issue to be closed once this version is available.

**Comment by DavidGrant-NIWC** [comment]
Fixed in FC 1.3, recommend close.

**Comment by JeffWootton** [comment]
Close Issue based on above comment.
