### ISSUE TITLE
Table 2-1 shows P for Dredged Area.  Only Surface is allowed.

### ISSUE THREAD

**Issue by tdepuyt** [iho-ohi/S-101-Documentation-and-FC#126]
Table 2-1 - Features permitted for ENC and their geometric primitives has Point allowed for Dredged Area.  Only Surface is allowed.  Remove P from the table for Dredged Area.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/11636423/b599b864-9d18-4c22-b83d-7720a7235030)

**Comment by JeffWootton** [comment]
Thanks for raising this issue Tom. This is an error in the Table and has now been corrected in the Master redline version of teh DCEG for Edition 2.0.0.

Close Issue.
