### ISSUE TITLE
Recommend adding text alignment to `TextPlacement`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#127]
Consider adding attributes to `TextPlacement` to allow data producers to specify the horizontal and vertical alignment of the label. Currently, the label is aligned on the horizontal and vertical center of the text in order to keep the text as close as possible to the anchor position while the chart is rotated.

### Text positioning for rotated charts example
In both cases the text is offset 6mm @ 45 degrees (relative to North) from the point at the center of the highlight:

Left/Bottom aligned:
|Alignment|North Up|South Up|
|:---|:---:|:---:|
|Left, Bottom|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/7acaa78d-a23b-4911-b9fd-bf7eca5bef85)|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/13038550-0092-4fb7-bc83-6d8129663107)|
|Center, Center|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/2be428ab-ae33-4711-b73c-0fa1148c7a45)|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/5dc8765e-cadd-4898-bcfd-b2af19c61c53)

**Comment by kusala9** [comment]
horizontal alignment would be useful for Chart 1 and some of the other test datasets in S-164 as it can be used for labels in the DS.

**Comment by TDYCARHugh** [comment]
If we add text alignment attributes then it will only work for North up and pretty much guarantee that it will be messed up when the screen is rotated.
If we automatically set the alignment based on the TextPlacement textOffsetBearing then it will work for North up and if a system is smart enough to automatically adjust the alignments with the Bearing + Rotation then the text might be ok even when course up.

See slides 3 and 4 from the presentation at S-100 WG8 item 3.6.
https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-100WG8/S100WG8_TextPlacement.pdf

**Comment by DavidGrant-NIWC** [comment]
> If we add text alignment attributes then it will only work for North up and pretty much guarantee that it will be messed up when the screen is rotated.

I'm trying to remember the use case I had in mind for this. I think I proposed this mainly to support specifying the alignment when the offset distance is zero, or when `textRotation`=`true`. It's possible I just proposed this because the PC implements Center, Center, but the original examples were for Start, Top.

I believe the guidance in S-100 5.2 Part 9 allows OEM's to adjust the alignment to "improve" the display, so maybe a text alignment attribute isn't needed.

At least for now I'll go ahead and close this; I'll re-open if I come across a better use case.

FYI, here's our implementation of auto-adjustment for rotated text; we don't currently adjust upright text.

|Chart Orientation|Requested Alignment|Adjusted Alignment|Result|
|:---:|:---:|:---:|:---:|
|0|Start, Center|Start, Center|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/eeead828-b6ac-465b-8e9d-23e0812b830a)
|45|Start, Center|Start, Center|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/ef6c2639-aa84-411f-b505-2b12899b244b)
|90|Start, Center|Start, Center|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/83aa5714-3d5f-4625-9846-8649ba7b9880)
|270|Start, Center|Start, Center|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/67bf3d46-4e34-4d78-b13a-47d6055254c5)
|315|Start, Center|End, Center|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/352b296c-f128-4a04-a0c8-18387655d82b)
