### ISSUE TITLE
`TextPlacement` can't position light name and description

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#129]
`TextPlacement` can position a feature name or a light description depending on the value of the `textType` attribute. Lights have both a name and a light description, but only one of these can be placed because the multiplicity of the binding to `TextAssociation` is always 0..1.

Recommend that the multiplicity of the binding from any light feature to `TextPlacement` via `TextAssociation` is modified to 0..2.

**Comment by TomRichardson6** [comment]
Support changing the multiplicity and note that Table 2-3 will also be affected in the DCEG.

**Comment by DavidGrant-NIWC** [comment]
> Would it be possible to get the feature name from the structure feature if the light feature itself doesn't have a feature name?

While that is possible, in my opinion the TextPlacement should be associated to the structure in that case.

**Comment by KlasOstergren-SMA** [comment]
> > Would it be possible to get the feature name from the structure feature if the light feature itself doesn't have a feature name?
> 
> While that is possible, in my opinion the TextPlacement should be associated to the structure in that case.

The problem with a text placement associated with the structure feature in this case is that the encoder then has to place two text placement features, which can be a challenge to get a good placement in areas with many features. If it were possible to encode a single text placement feature (with textType = 1,2) with the name is portrayed on one line and the light description on a second line, it would make life much easier for the data producers and give a better result for the ECDIS user.

**Comment by DavidGrant-NIWC** [comment]
> [...] which can be a challenge to get a good placement in areas with many features. [...]

We should not expect the PC to do a better job than is possible using manual placement.

**Comment by TDYCARHugh** [comment]
Perhaps if there is a TextPlacement on the structure with an appropriate textType then all the texts of equipment features could be stacked at that one location.  One issue is that textType has a multiplicity of 1 so you cannot assign textType =1,2.

**Comment by KlasOstergren-SMA** [comment]
> > [...] which can be a challenge to get a good placement in areas with many features. [...]
> 
> We should not expect the PC to do a better job than is possible using manual placement.

Of course, the end result will never be better than the combination of the data and portrayal rules. 
The problem with placing two separate features on two lines is that when you zoom out, the text will clash with each other (unless you are not implementing complex alignment rules in the portrayal catalogue. If one feature is used to label two texts on separate lines, the text on those two lines will never clash.

**Comment by DavidGrant-NIWC** [comment]
> [...] those two lines will never clash [...]

True, not with each other. But they may still clash with other labels on the feature or with labels on adjacent features as the chart is zoomed and/or rotated.

> [...] when you zoom out, the text will clash [...]

Because both text placement features would (I assume) normally be offset from the same geographic position (of the structure/equipment) by a distance specified in mm, I don't believe the text will clash with each other when zooming. However, the text probably will clash as the chart is rotated depending how the bearing / distance is specified and whether the chart was evaluated at different orientations.

**Comment by JeffWootton** [comment]
To be discussed as part of S-101PT13 Agenda item 07.8.

**Comment by JeffWootton** [comment]
Remodelling of `TextPlacement` as agreed at S-101PT13 resolves this issue.

Close Issue.
