### ISSUE TITLE
ECDIS Viewing Scales

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#13]
During our meeting on 16 November 2021, it was decided to take an action in view of mandating a minimum list of viewing scales in ECDIS systems, to be consistent with the scale minimum policy.
Not being an ECDIS specialist, I think it would be helpful to have some details from the OEMs (of course all of you can provide inputs) on the following items:
- What is the list of viewing scales proposed in your systems?
- Do you have any feedback on this?
- Do mariners often use the "Drag to zoom" and consequently have the data displayed at a "non-standard scale"?
- How discrete is the "zoom in/out in your system? (I think it is interesting to compare to the scale minimum values).
- Any comment on the current S-57 SCAMIN policy? (S-101 scale minimum is the same so far).

**Comment by JeffWootton** [comment]
Issue has now been open for over 12 months with no feedback.  Close pending further input.
