### ISSUE TITLE
FloatingDock - Discontinue Geometric primitive of type Point

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S-101-Documentation-and-FC#133]
This issue is created as a result of a decision made by NCWG9 when discussing the following Portrayal sWg issue:
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/141 

**Outcome: NCWG recommends retaining the S-57 approach not allowing a point feature.**

**Comment by JeffWootton** [comment]
I am not sure I agree with this decision by the NCWG.

S-4 clause B-326.2 is as follows:

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/9964a16c-90e0-4bf8-a24b-e2fc05c45393)

The statement "when the symbol is reduced to minimum size" implies, to me, that the 4mm symbol at INT1 - F26(b) is intended to be a point symbol. Or is it not intended to show a floating dock on an ENC when the scale reduces the size to less than 4mm?

It should also be noted that one of the reasons that point was introduced into S-101 is in recognition of the symbol at INT1 - F26(b) as well as the fact that `FloatingDock` has been removed from the Skin of the Earth in S-101 and a point symbol has always been available for the `Hulk` feature.

From the perspective of the last point above, I feel there is an inconsistency if we allow the encoding of point for `Hulk` and not for `FloatingDock`.

**Comment by benhazelgrove** [comment]
Agree to retain point geometry and development of a new symbol.

**Comment by JeffWootton** [comment]
S-101PT13: Agreed to remove point as an allowable geometric primitive for `FloatingDock` (refer to Decisions related to Paper S-101PT13-06.1). Applied for S-101 Edition 1.4.0.

Close Issue.
