### ISSUE TITLE
Helipad as an equipment feature

### ISSUE THREAD

**Issue by MikkoHovi-FI** [iho-ohi/S-101-Documentation-and-FC#136]
DCEG Clause 14.1.1 on Offshore platforms says: "_Platforms may carry lights (see Section 19), fog signals (see clause 20.19), helicopter landing pads (see clause 6.5) and flare stacks._" However, unlike with lights and fog signals, the it's not possible to have a Helipad as equipment for the Offshore platforms. Should it be?

I'm asking this, as we have in a similar manner helipads on some offshore lights (LNDMRKs, BCNSPPs) and in S-57 those have been encded as RUNWAYs with and a master-slave relationship with the LNDMRK/BCNSPP. This has loosely been based on a S-57 UOC clause on OFSPLF similar to the DCEG clause above.

So, the question is: should there be a Structure/Equipment relationship possible between Helipad and Offshore platform? And if, could it also be added between Helipad and Landmark, and Helipad and Special Purpose/General Beacon? 

We would find it useful as the option is that we use Information attribute to store this - as compared to a proper feature in S-57.

**Comment by JeffWootton** [comment]
Have added `Helipad` as an allowable feature for inclusion in the association `Structure/Equipment`. Addition of `Helipad` as an equipment feature for `Landmark`, `Special Purpose/General Beacon` (and possibly `Building`?) to be discussed at S-101PT13.

**Comment by JeffWootton** [comment]
S-101PT13: Recommendations as included in Paper S-101PT13-06.1 and draft DCEG Edition 1.4.0 approved.

Close Issue.
