### ISSUE TITLE
Distance Mark

### ISSUE THREAD

**Issue by HermanSchouten** [iho-ohi/S-101-Documentation-and-FC#139]
For 1.3 Change Guidance where it says “must” be associated to the structure to “may” be associated to a structure.
Distance mark has a structure feature in it's definition: A distance mark indicates the distance measured from an origin and consists of either a solid visible structure or a distinct location without special installation.

The Boolean attribute Distance mark visible should control the presentation of the feature in S-101.
In S-57 S-52 portrayal there are 2 symbols. 1 for physical and 1 for non physical (Also in S-4). This will be slightly different in S-101 where the boolean attribute is either visible or non visible. Currently this does not work in that manner.

Adding a parent feature results in extra workload in compiling and/or post conversion manual adjustments. It also results in clutter on the screen.

**Comment by HermanSchouten** [comment]
Is it correct that current draft presentation in S-101 for both visible and not visible DistanceMark is the following:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/90600414/e93044c8-82b6-4e0b-97c6-8ddcd166350a)

In S-57/S-52 there are the following two symbols, the first for Physical and the 2nd for Non Physical:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/90600414/d0c9a423-ec47-4216-9125-11f4f10d2956)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/90600414/aac35d19-f92e-4878-a419-70488ec91331)

**Comment by DavidGrant-NIWC** [comment]
The 1.2 S-101 PC does not use the `distanceMarkVisible` attribute to affect the portrayal.

|`StructureEquipment`|Mark (magenta circle)|Text offset|Text horizontal alignment|
|:---:|:---:|:---:|:---:|
|No association|Shown|3.15mm right of symbol|Start|
|Has association|Not Shown|7.02mm left of symbol|End|

**Comment by HermanSchouten** [comment]
Hi David, thank you.
I Guess this means there is no equivalent to a non physical Distance Mark in S-101 then. 

S-52 portrayal was not aligned with S-4 . (Magenta for a physical feature with no effects to it's surroundings is a bit strange)
S-101 Should/Could align better with S-4.  
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/90600414/b4434c1e-1664-4c90-9aab-f4f5c768bbf1)
Should the _distance unit of measurement_ also be taken into account?

**Comment by HermanSchouten** [comment]
Thanks again David.
I like Your example of a visible distance mark., that is a clear situation where you would have a Parent feature which is worth encoding. In our case 90% of the Distance marks are just minor posts which do not have a Parent feature. Or could be a Distance mark painted on the Quay (SLCONS) it is visible but without Parent feature.  In such cases you still would want black instead of magenta display.

**Comment by DavidGrant-NIWC** [comment]
> In such cases you still would want black instead of magenta display.

You would need to raise that issue in the PSWG GitHub: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues

**Comment by JeffWootton** [comment]
Attribute `distanceMarkVisible` in the draft DCEG has been amended from optional to mandatory and the guidance amended to state that a structure feature **may** be associated to the distance mark (was formerly "must").

This change in the modelling and guidance is intended to allow for encoding of visible distance marks that have no structure feature at the position of the distance indication as outlined by Herman above. The mandating of `distanceMarkVisible` is intended to allow for this attribute to be considered in ECDIS portrayal. For example, the existing portrayal rules may be retained with the added condition that if the `DistanceMark` has `distanceMarkVisible` populated as _True_ and is not in a `Structure/Equipment` relationship, then the (black) position circle at the position of the mark is retained in the display.

For consideration at S-101PT13 and possible action for the Portrayal Sub-Group.

**Comment by JeffWootton** [comment]
S-101PT13: Recommendations as included in Paper S-101PT13-06.1 and draft DCEG Edition 1.4.0 approved.

Close Issue.
