### ISSUE TITLE
DCEG/FC: entries where valueType is numeric should not have format/textPattern restriction

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#147]
depthRangeMinimumValue, depthRangeMaximumValue, etc.

The patterns shown in the DCEG are inconsistent (the leading sign is not always shown). The range constraint should be used to restrict the value space when necessary, rather than indicating that the sign may/may not be present. The precision constraint should be used to restrict the number of digits in the encoding.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/650ad8bf-e4fb-48e2-b753-84dc8963043b)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/ce2303a4-d249-44e8-9e39-eb95288f85cc)

**Comment by JeffWootton** [comment]
All numeric type attributes have now been amended in the GI Registry and the DCEG to conform with the conventions in S-100.

Close Issue.

**Comment by DavidGrant-NIWC** [comment]
Please re-open until the FC is fixed (or create a separate issue)
