### ISSUE TITLE
DCEG: Recommend adding note that reported anchorages MUST be encoded as points

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#149]
Surface geometry is not supported for reported anchorages:
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/72#issuecomment-1185172041

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/99893d3f-333e-4cd9-8602-20d9c7d3bac6)

**Comment by JeffWootton** [comment]
Have added the following at clause 16.3.1:

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/59912d67-f39c-4e89-b6e7-db20999a3a6f)

For discussion and approval at S-101PT13.

**Comment by JeffWootton** [comment]
S-101PT13: Change approved.

Close Issue.
