### ISSUE TITLE
Portrayal Attribute Clarity

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-101-Documentation-and-FC#15]
S-101 1.0.2 contains a number of Portrayal Attributes (2.4.5.1). Although these are described in the DCEG there is no specific definition of how these values are calculated. To avoid inconsistent implementation in production tools I would like to propose that 2.4.5.1 is expanded to provide detailed descriptions of how these values are calculated with examples. Depending on the space needed it may be more appropriate to includes these in detail within each attribute section and reference from 2.4.5.1. It may be useful to use graphics such as UML to convey these.

If comments on this proposal are positive I will start drafting the text.

**Comment by alvarosanuy** [comment]
Agree . The 'how to' calculate portrayal attributes has to be standardised and documented.

**Comment by JeffWootton** [comment]
Refer to Action S-101PT9-05 and new S-101 Documentation and FC Issue #77. Close Issue.
