### ISSUE TITLE
Review of Draft 1.3.0 Feature Catalogue

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-101-Documentation-and-FC#151]
A draft 1.3.0 Feature Catalogue has been posted here, comments are invited on this document. Please comment here with any issues that you identify.

[S-101-Documentation-and-FC/S-101FC/FeatureCatalogue.xml at main · iho-ohi/S-101-Documentation-and-FC (github.com)](https://github.com/iho-ohi/S-101-Documentation-and-FC/blob/main/S-101FC/FeatureCatalogue.xml)

**Comment by DavidGrant-NIWC** [comment]
The FC references the staging server (because that’s the only place the 5.2 schema is available). The 5.2 schemas need to be moved to the production server and then the FC should be updated accordingly.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/6a590d40-06fd-47ef-9eb5-1173613fed9f)

**Comment by TomRichardson6** [comment]
Some initial observations on this draft, review not yet completed. 

@DavidGrant-NIWC agree that this will need to be amended in the final 1.3.0 Catalogue. 

XML line 8527 DCEG ref 27.125

Change - Corrected the definition of attribute maximum permitted vessel length to refer to length rather than draught.

Observation - Definition continues to refer to draught should be amended to length. 

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71879917/80ed99d9-59a7-48a6-bb1d-b3a2edac2cd8)

XML line 8554 DCEG ref 28.10

Change - Amended attribute type for attribute measurement distance maximum from type Real to type Integer.

Observation - Value type is still listed as Real should be Integer

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71879917/235f29d2-902e-484a-9249-2fea60e9afb3)

XML line 8569 DCEG ref 28.11

Change - Amended attribute type for attribute measurement distance minimum from type Real to type Integer.

Observation - Value type is still listed as Real should be Integer

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71879917/2322a914-0e83-4a0f-8e5e-8fe8d7cbcb08)

**Comment by DavidGrant-NIWC** [comment]
#144 and #145 are uncorrected.

**Comment by TDYCARHugh** [comment]
Agree with David's comment that textPattern fields are not currently valid Regex.

Feature binding from features to TextPlacement should have an association roleType of 'association'  from TextPlacement to feature should be roleType = 'composition'.  This was correct in 1.2 but got reversed in 1.3 draft.

`			<S100FC:featureBinding roleType="composition">
				<S100FC:multiplicity>
					<S100Base:lower>0</S100Base:lower>
					<S100Base:upper xsi:nil="false" infinite="false">1</S100Base:upper>
				</S100FC:multiplicity>
				<S100FC:association ref="TextAssociation" />
				<S100FC:role ref="theCartographicText" />
				<S100FC:featureType ref="TextPlacement" />
			</S100FC:featureBinding>
`
should be 
`<S100FC:featureBinding roleType="association">`

UpdatedInformation association.  From feature to UpdateInformation with role 'theUpdate' should be 0 to many as in DCEG.

`			<S100FC:featureBinding roleType="association">
				<S100FC:multiplicity>
					<S100Base:lower>0</S100Base:lower>
					<S100Base:upper xsi:nil="false" infinite="false">1</S100Base:upper>
				</S100FC:multiplicity>
				<S100FC:association ref="UpdatedInformation" />
				<S100FC:role ref="theUpdate" />
				<S100FC:featureType ref="UpdateInformation" />
			</S100FC:featureBinding>
`
should be:
`<S100Base:upper xsi:nil="true" infinite="true" />`

Inconsistencies with DCEG: names of roles are not exactly matching  for example ‘theUpdate’ versus the The Updated Object.   It would be nice to actually have the proper camel case codes for features, attributes, roles etc. listed in the DCEG for consistency with the FC.

Also noticed a DCEG error: Under CautionArea the CautionAreaAssociation association to Archipelagic Sea Lane should be using the role 'theComponent' and multiplicty of 0..*.

**Comment by TomRichardson6** [comment]
Two further comments 

DCEG ref 27.184

The definitions for rectangle (horizontal) and rectangle (vertical) have not been updated to be consistent with the DCEG.
<img width="576" alt="Untitled" src="https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71879917/20f108df-b77b-4e13-933f-e566463e01c6">
<S100FC:listedValue>
					<S100FC:label>Rectangle (Horizontal)</S100FC:label>
					<S100FC:definition>Where the two longer opposite sides are standing horizontally. A rectangle is a plane figure with four right angles and four straight sides, opposite sides being parallel and equal in length. A horizontal rectangle is where the two longer opposite sides are standing horizontally.</S100FC:definition>
					<S100FC:code>20</S100FC:code>
					<S100FC:definitionReference>
						<S100FC:sourceIdentifier>1143</S100FC:sourceIdentifier>
						<S100FC:definitionSource ref="IHOREG" />
					</S100FC:definitionReference>
				</S100FC:listedValue>
				<S100FC:listedValue>
					<S100FC:label>Rectangle (Vertical)</S100FC:label>
					<S100FC:definition>A rectangle is a plane figure with four right angles and four straight sides, opposite sides being parallel and equal in length. A vertical rectangle is where the two longer opposite sides are standing vertically.</S100FC:definition>
					<S100FC:code>21</S100FC:code>
					<S100FC:definitionReference>
						<S100FC:sourceIdentifier>1144</S100FC:sourceIdentifier>
						<S100FC:definitionSource ref="IHOREG" />
					</S100FC:definitionReference>
				</S100FC:listedValue>

DCEG ref 27.192

Linked to the other comment on Regex for textPattern the change of value of sounding from 0.01 to 0.1 has not been reflected in the FC. Propose that a broader review and update of all textPattern  values is needed for FC 2.0.0.

**Comment by TDYCARHugh** [comment]
I think that the roles for TextPlacement TextAssociation  might be backwards.
Currently it is defining that the TextPlacement feature is referred to as 'theCartographicText' and the feature for which the text is being placed is being referred to as 'thePositionProvider'.   It seems to read better if these were swapped in the bindings each way.  I would have preferred simpler roles like 'thePlacement' and  'theFeature'.

**Comment by gorogara** [comment]
@TomRichardson6 
Updated lists
1. Maximum Permitted Vessel Length
https://github.com/bluemap-github/S-101-Documentation-and-FC/commit/0c85ae8ed19ed5cd71be073153ebdf57b23d44e3

2. Measurement Distance Maximum(&Minimum)
https://github.com/bluemap-github/S-101-Documentation-and-FC/commit/6d3278c2600db9dbc1a0b9657e5aa4b75afe9af3

3. Rectancle (Horizontal & Vertical)
https://github.com/bluemap-github/S-101-Documentation-and-FC/commit/5353489056982aca1bd5a561a1cd6ac08917d266

**Comment by rmalyankar** [comment]
> @TomRichardson6 Questions List
> 
> 1. Precision of value of sounding
>    If the precision of the value of sounding is 0.1, should it be entered as `<S100CD:precision>1</S100CD:precision>` in the FC?
>    And would `<S100CD:precision>2</S100CD:precision>` correspond to 0.01.

I am not Tom, but yes, precision 0.1 and 0.01 would be entered in an FC as 1 and 2 respectively. Note that the type of _precision_ in S-100 is "non-negative integer".

> 2. Precision of other attributes
>    It seems that the precision of other attributes can be updated by retrieving the registered values from the GI Registry.
>    Should the updates be made using the values from the GI Registry?

This may be more complicated. I think the registry may be missing entries for _precision_ or have the wrong format ("0.01") in some cases. In case of conflict between the registry and the DCEG, the DCEG should prevail.

**Comment by DavidGrant-NIWC** [comment]
The correct value to use for precision is not well defined. See https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/104#issuecomment-2016046518
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/77af3574-86d0-426b-a2ff-07928a615c9d)

**Comment by TDYCARHugh** [comment]
TextPlacement binding with role theCartographicText should be roleType association, association from TextPlacement to feature is roletype composition.

**Comment by TomRichardson6** [comment]
@gorogara 

Responses on your questions please apply these but no need to prepare a further version at this time. 

1. Please use 1 and I will take an action to explore this further and confirm. This will eventually need clarity in S-100. 

2. Yes in future but no action at this stage we need to confirm the approach to precision. As Raphael says the Registry needs checking as well. 

3. Yes please apply this change as per Hugh's comment. 

4. Please retain this as consistent with the DCEG until a further version of the DCEG is prepared.

**Comment by TomRichardson6** [comment]
Closing as completed now superseded by edition 1.4.1
