### ISSUE TITLE
New S-101 Attribute drawingIndex - Implementation and Testing

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#152]
A new attribute drawingIndex has been added to the S-101 feature DataCoverage in S-101 Edition 1.3.0 (draft for Edition 2.0.0) for implementation and testing. The intention of this attribute is assist in identifying in the S-101 ECDIS rendering (display) algorithm the S-101 data coverages that are intended by the Data Producer to be displayed seamlessly in the ECDIS. [NOTE: In previous Editions of S-101, identification of data coverages to be displayed seamlessly is intended to be achieved through population of common values for the minimumDisplayScale attribute.]

This Issue is intended for S-101PT Members and Implementers to discuss the addition of drawingIndex and provide any feedback in implementation and testing.

Please refer to S-101 Main document clause 4.5.2 and Annex D - clause D-3; and S-101 DCEG (Edition 1.3.0) clauses 2.4.5, 2.5.5, 3.5 and 28.3.

**Comment by benhazelgrove** [comment]
In CARIS 5.0.1, editing of the S-101 catalogue is not supported, so the addition of the drawingIndex attribute hasn't been tested by AHO.

**Comment by JeffWootton** [comment]
S-101PT13: Approved to include for S-101 Edition 2.0.0.

Close Issue.
