### ISSUE TITLE
DCEG & FC: `RadarStation` is missing an association to `ContactDetails`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#154]
[Related PC issue](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/368)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/adf8f68a-e731-428d-b250-7378037d5a25)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/b0758c03-afaa-4cd4-9d90-02852cd17ad0)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/5fdc8c14-f97f-4b53-bfd4-43e0201e9ad2)

**Comment by JeffWootton** [comment]
@DavidGrant-NIWC: An interesting question. The simple answer to this is yes as the scenario that you have described is not prohibited in the DCEG.

This has not been raised before. I suppose a similar situation exists for the the attribute `pictorialRepresentation` and the complex attribute `information`, which can also be encoded on individual features and on the information type `NauticalInformation`. The question I have is - does this cause any issue in regard to ECDIS portrayal/performance?

On investigation, in addition to `RadarStation`, the features `PilotageDistrict`, `RadarRange`, `RadioStation`, `SignalStationTraffic` and `SignalStationWarning` also require association to `ContactDetails`. I have applied all the appropriate changes to the DCEG, however will keep this Issue open pending any further discussion on the above.

**Comment by JeffWootton** [comment]
This change will not be in the 1.3 Feature Catalogue as it is aligned to the 1.3 DCEG which has been "published". The change has been made for Edition 1.4 (which can be published anytime if considered necessary), so will be in the 1.4 FC.

**Comment by DavidGrant-NIWC** [comment]
Fixed in 1.4 FC.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/7bd69435-d92c-43ca-99a5-673237924052)
