### ISSUE TITLE
DCEG: default value for `flareBearing`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#155]
The values seem backwards, shouldn't the default be 135 and the override 45?
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/b844dcb1-5614-4489-9b2a-129708204b45)

**Comment by HermanSchouten** [comment]
In Cartography generally 45 is the default for Fixed features, 135 for floating features.

**Comment by JeffWootton** [comment]
The DCEG has been corrected to agree with the S-52 CSP:

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/f7c69e8d-b0a0-45e8-980a-c6b093ba640f)

Close Issue. Further discussion regarding attribute flareBearing to take place under Issue #121 .
