### ISSUE TITLE
Review of Draft 1.3.1 Feature Catalogue

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#157]
A draft 1.3.1 Feature Catalogue has been posted here. Comments are invited on this document. Please comment here with any issues that you identify.

[S-101-Documentation-and-FC/S-101FC/FeatureCatalogue.xml at main · iho-ohi/S-101-Documentation-and-FC (github.com)](https://github.com/iho-ohi/S-101-Documentation-and-FC/blob/main/S-101FC/FeatureCatalogue.xml)

**Comment by DavidGrant-NIWC** [comment]
I closed issues which are corrected by this FC (or prior). Any open issue in this repo which was originated by me and which applies to the FC is uncorrected in this release:
#140, #141, #144, #145, #147, #148, #154, #156

**Comment by rmalyankar** [comment]
See below for warnings reported by updated FC check rules.  Some can be ignored, for example the warnings about no UoM for drawingIndex, etc., but others may need to be addressed.

| Warnings reported by updated FC check rules|
|--------|
|	Attribute drawingIndex (integer) has no UoM, verify omission of UoM	|
|	Attribute maximumDisplayScale (integer) has no UoM, verify omission of UoM	|
|	Attribute measuredDistance (integer) has no UoM, verify omission of UoM	|
|	Attribute minimumDisplayScale (integer) has no UoM, verify omission of UoM	|
|	Attribute numberOfFeatures (integer) has no UoM, verify omission of UoM	|
|	Attribute scaleMinimum (integer) has no UoM, verify omission of UoM	|
|	Attribute scaleValueMaximum (integer) has no UoM, verify omission of UoM	|
|	Attribute scaleValueMinimum (integer) has no UoM, verify omission of UoM	|
|	Attribute updateNumber (integer) has no UoM, verify omission of UoM	|
|	Attribute textOffsetDistance (integer) has no UoM, verify omission of UoM	|
|	Attribute uncertaintyVariableFactor (real) has no UoM, verify omission of UoM	|
|	Attribute underlyingLayer (integer) has no UoM, verify omission of UoM	|
|	Attribute waterwayDistance (real) has no UoM, verify omission of UoM	|
|	Attribute optimumDisplayScale (integer) has no UoM, verify omission of UoM	|
|	Attribute depthRangeMaximumValue: textPattern used with real datatype	|
|	Attribute depthRangeMinimumValue: textPattern used with real datatype	|
|	Attribute magneticAnomalyValue: textPattern used with real datatype	|
|	Attribute sectorBearing: textPattern used with real datatype	|
|	Attribute speedLimit: textPattern used with real datatype	|
|	Attribute textOffsetBearing: textPattern used with integer datatype	|
|	Attribute textOffsetDistance: textPattern used with integer datatype	|
|	Attribute buriedDepth: precision not used with 'real' datatype	|
|	Attribute defaultClearanceDepth: precision not used with 'real' datatype	|
|	Attribute depthRangeMaximumValue: precision not used with 'real' datatype	|
|	Attribute depthRangeMinimumValue: precision not used with 'real' datatype	|
|	Attribute elevation: precision not used with 'real' datatype	|
|	Attribute estimatedRangeOfTransmission: precision not used with 'real' datatype	|
|	Attribute height: precision not used with 'real' datatype	|
|	Attribute horizontalClearanceLength: precision not used with 'real' datatype	|
|	Attribute horizontalClearanceValue: precision not used with 'real' datatype	|
|	Attribute horizontalClearanceWidth: precision not used with 'real' datatype	|
|	Attribute horizontalDistanceUncertainty: precision not used with 'real' datatype	|
|	Attribute horizontalLength: precision not used with 'real' datatype	|
|	Attribute horizontalWidth: precision not used with 'real' datatype	|
|	Attribute iceFactor: precision not used with 'real' datatype	|
|	Attribute liftingCapacity: precision not used with 'real' datatype	|
|	Attribute magneticAnomalyValue: precision not used with 'real' datatype	|
|	Attribute maximumPermittedDraught: precision not used with 'real' datatype	|
|	Attribute maximumPermittedVesselLength: precision not used with 'real' datatype	|
|	Attribute orientationUncertainty: precision not used with 'real' datatype	|
|	Attribute radius: precision not used with 'real' datatype	|
|	Attribute sectorBearing: precision not used with 'real' datatype	|
|	Attribute sectorLineLength: precision not used with 'real' datatype	|
|	Attribute signalDuration: precision not used with 'real' datatype	|
|	Attribute signalPeriod: precision not used with 'real' datatype	|
|	Attribute sizeOfFeaturesDetected: precision not used with 'real' datatype	|
|	Attribute speedMaximum: precision not used with 'real' datatype	|
|	Attribute speedMinimum: precision not used with 'real' datatype	|
|	Attribute streamDepth: precision not used with 'real' datatype	|
|	Attribute surroundingDepth: precision not used with 'real' datatype	|
|	Attribute timeRelativeToTide: precision not used with 'real' datatype	|
|	Attribute uncertaintyVariableFactor: precision not used with 'real' datatype	|
|	Attribute valueOfAnnualChangeInMagneticVariation: precision not used with 'real' datatype	|
|	Attribute valueOfDepthContour: precision not used with 'real' datatype	|
|	Attribute valueOfMagneticVariation: precision not used with 'real' datatype	|
|	Attribute valueOfMaximumRange: precision not used with 'real' datatype	|
|	Attribute valueOfNominalRange: precision not used with 'real' datatype	|
|	Attribute valueOfSounding: precision not used with 'real' datatype	|
|	Attribute verticalClearanceValue: precision not used with 'real' datatype	|
|	Attribute verticalLength: precision not used with 'real' datatype	|
|	Attribute waterwayDistance: precision not used with 'real' datatype	|
|	Attribute waveLengthValue: precision not used with 'real' datatype	|
|	Attribute minimumBerthDepth: precision not used with 'real' datatype	|
