### ISSUE TITLE
Rename attribute bridgeConstruction to bridgeStructureType

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#158]
A question has been raised by the Defence Geospatial Information Working Group (DGIWG) to rename the S-101 attribute bridgeConstruction to the corresponding DGWIG attribute name bridgeStructureType.

The attributes are very similarly defined (in fact, if this proposal is accepted it is suggested that the renamed S-101 attribute also adopts the DGIWG definition):

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/009c440f-7ab8-4a59-a2ca-c77244c82eb1)

DGWIG: Definition: The type(s) of structural design of a bridge, bridge span, or bridge superstructure.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/3bfe3ae9-f18b-4bf5-913a-fd62aa047523)

It is considered that discussion on proposals such as this will contribute to consistency and harmonization between IHO (S-101) and other marine-based data models.

Similarly, it has been identified that the S-101 attribute categoryOfOpeningBridge is very similar to the DGIWG attribute bridgeOpeningType. Similar consideration may be given to amending the attribute name in S-101.

**Comment by Christian-Shom** [comment]
In S-101, many attributes are "category of ..."
In DGWIG standard, many attributes are "... type": Bridge Opening Type, Hydrographic Light Type, Maritime Track Type, etc.

Although I agree that we should look at harmonization, I wonder if we would not be opening the door to many changes, and finally bring inconstancy in S-101 attribute naming.

**Comment by benhazelgrove** [comment]
It seems that the DGWIG concepts are not in the GI registry, therefore we think that the S-101 concepts take priority as they are already registered. Agree with SHOM

**Comment by JeffWootton** [comment]
Tend to agree with Christian's comment. Staring this process of alignment of concept names between S-101 and the DGIWG at this stage without a full systematic investigation will cause increasing inconsistencies in concept names in both S-101 and the IHO GI Registry.

Perhaps as a first step the DGWIG names can be included as an alias in the Registry?

**Comment by JeffWootton** [comment]
S-101PT13: Agreed to retain current Item Name and add "Bridge Structure Type" as an Alias (refer to Action S-101PT13/24 - Complete).

Close Issue.
