### ISSUE TITLE
Overscale indication

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#16]
In the current S-101 documentation, it is stated that:

- The Max Display Scale is considered to be the equivalent of the compilation scale of the data (PS §4.5.3)
- The overscale indication must be shown when the viewing scale is larger than the Max DS (PS §4.6)

This does not "allow" a factor 2 zoom as it is currently with S-57 ENCs and will trigger an overscale indication in cases such as this one (for Data Coverage 2):
![image](https://user-images.githubusercontent.com/71139640/176903539-e872a32a-d60d-4bd2-b3cf-2c559d26faec.png)

I suggest changing the wording in the standard to allow a factor 2 zoom from the Max DS.

**Comment by alvarosanuy** [comment]
My understanding is that overscale factors are calculated and presented as an ECDIS Indication (text on the border of the screen) once the MSVS becomes larger than one of the maxDS **but**, the overscale pattern (prison bars), is only triggered when the loading strategy builds the display using different dataCoverages and one (or more) of them have a maxDS that has been 'grossly overscaled' (> 2X). When the mariner deliberately enlarges the ENC by more that 2X, the overscale Indication will continue to display but the overscale pattern (prison bars) shouldn't display and clutter the whole screen.
Technically then, the statement in S-101 PS 4.6 is correct, although it explains half of the story .....
Refer to S-98 Annex C section C-12.1.2 (seems to be a copy/close translation of what is described in S-52 Part I.

**Comment by Christian-Shom** [comment]
Sub-Group meeting 2022-10-19 agreed on:

- For Edition 1.1.0, Both the overscale indication (text on the border of the screen) and overscale pattern (Prison bars on the Data Coverage feature(s) concerned) should be present as soon as at least one of the Data Coverage features that participate in the display has a Maximum Display Scale that is smaller than the display scale on the graphics window.

**Comment by JeffWootton** [comment]
Refer to S-101 Edition 1.1.0 Main document, clause 4.6, Close Issue pending further feedback from implementation and testing.
