### ISSUE TITLE
Support files metadata attribute S100_ResourcePurpose updating

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/S-101-Documentation-and-FC#160]
Summarizing the attributes S100_ResourcePurpose proposal for S-101 PS for the discussion/agreement :

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/72803214/7baab8d8-1015-47ba-92c2-56840ee533e5)

When agreed/discussed for this table here, the texts in the PS and the DCEG can be updated accordingly. 
This is not a proposal to add text in the Remarks field, it is a proposal with which type of Support file the corresponding supporting resource can be identified.

**Comment by MikusRL** [comment]
Assuming we can agree that the supportFile (Code1) associates only with the dataset (ENC) Support file, I suggest to update the Description field for supportFile - from 
"A support file"
 to 
"The dataset (ENC) support file."
and adding a comment in the Remarks field:
"It must be referenced within the dataset's attributes."

**Comment by rmalyankar** [comment]
The concepts of "ENC support file" and "system support file" are too vague.

**Comment by MikusRL** [comment]
> The concepts of "ENC support file" and "system support file" are too vague.

@rmalyankar any other suggestions to be able to describe the functionality and expected implementation of the two through the distribution and in the end user systems clearer than of today throughout the Standards and the product specifications?

**Comment by rmalyankar** [comment]
I had proposed S100_SupportedResourceType (? or some such name) with a detailed list of types of resources supported (including 'system' at the top level, if my recollection is correct), but the S-100 working group decided to simplify it into what we have today. I will try to find that. It is however too late to reintroduce it into 5.2.

Offhand options:

1.  Define the URI structure used in the _fileName_ attribute of S100_SupportFileDiscoveryMetadata to distinguish between different types of support files, drawing perhaps on the list I mentioned above.
2.  Define a URI structure (MRN structure) to distinguish (ENC?) datasets from other types of resources, specifically, FC (for language packs - "product specification version"?), and all S-100 apps ("system"?),  etc.  and use it in _supportedResource_ (make _supportedResource_ mandatory). If you just want to distinguish files supporting datasets from other files all the application/distribution needs to do is treat every value of _supportedResource_ not indicating a dataset as 'other'.

**Comment by MikusRL** [comment]
Happy to discuss this today in the VTC. 
In general the No.1 option is one option how this could be done, but to be able to describe that, one needs a simple general first granularity division to justify the difference. I think with two simple ones would be enough, but if there is a clear need for a third or fourth one as well, and everyone agrees, then it is fine. But what I am also saying is that there not necessarily need to be a literal division also exactly like that in the model. It is needed only in the PS texts, and could be mentioned in the Remarks fields in the tables, if that helps to read and implement the appropriate support.

Regarding the No.2 option I think that it is clear already as it is and should be only improved if you have found any issues there. Again I would argue that in describing this it needs to be pointed out that for System Support files (self-standing files) that is what is or should be mandatory. As we have indicated earlier in our presentation that in some Dataset support file usecases, it actually for _Dataset_ Support files should be discouraged or completely forbidden to be used. And nothing is wrong with either of the usecases - it just would make it possible to distinguish and describe appropriately both usecases in PS and the correct encoding for it in the DCEG.

**Comment by MikusRL** [comment]
In the 03.06.2024 VTC call (@DavidGrant-NIWC , @rmalyankar , @skjeves, Su Marks , @kusala9, @MikusRL ) it was agreed that:

- against "support File" in Remarks field is stated that this format is only possible as **_ENC Support file_**;
- against "ISO Metadata" in Remarks field is stated that this is irrelevant and not to be used in S-101 PS;
- against "Language Pack" in Remarks field is stated that this format is only possible as **_System Support file_**;
- against "GML Schema" in Remarks field is stated that this is irrelevant and not to be used in S-101 PS;
- against "other" in Remarks field is stated that this format is only possible as **_System Support file_**;

**Comment by MikusRL** [comment]
Agreed and finalized through #159
