### ISSUE TITLE
Support files metadata attribute S100_SupportFileFormat

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/S-101-Documentation-and-FC#161]
Summarizing the attributes S100_SupportFileFormat proposal for S-101 PS for the discussion/agreement:

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/72803214/04da7b19-69a2-4d7b-a101-7e1559310757)

When agreed for this table here, the texts in the PS and the DCEG can be updated accordingly.
This is not a proposal to add a concrete text in the Remarks field, it is a proposal with which type of Support file the corresponding support file format can be identified.

**Comment by rmalyankar** [comment]
The concepts are too vague as I also remarked in #160.

Also, what exactly is so scary about having ENCs reference HTML files? It is simple enough to make rules about links or no links, not referencing offsite content, etc., and restricting the set of HTML tags allowed, and simple enough to check those rules automatically.

This is a simple valid html file:

```html
<!DOCTYPE html>
<html lang="la">
<head>
  <meta charset="utf-8"/>
  <title>Optional descriptive title</title>
</head>
<pre>
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere,
magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna.

Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus.Pellentesque habitant morbi tristique senectus
et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede. Mauris et orci.

Aenean nec lorem. In porttitor. Donec laoreet nonummy augue. Suspendisse dui purus, scelerisque at,
vulputate vitae, pretium mattis, nunc. Mauris eget neque at sem venenatis eleifend. Ut nonummy.
</pre>
</html>
```

**Comment by MikusRL** [comment]
In the 03.06.2024 VTC call (@DavidGrant-NIWC , @rmalyankar , @skjeves, Su Marks , @kusala9, @MikusRL ) it was agreed that:

- against TXT UTF-8 format in Remarks field is stated that this format is only possible as **_ENC Support file_**;
- against JPEG2000 format in Remarks field is stated that this format is prohibited for use in S-101 PS;
- against HTML format in Remarks field is stated that this format is irrelevant and not used in S-101 PS at this stage;
- against XML format in Remarks field is stated that this format is only possible as a **_System Support file_**
- against TIFF format in Remarks field is stated that this format is only possible as an **_ENC Support file_**
