### ISSUE TITLE
`fileLocator` attribute

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#162]
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/c6eed8bd-380e-482e-9106-5dcd3fed62db)

1. Reference to S100_SupportFileFormat should be to _S-100 Part 17 clause 17-4.5 Elements of the Exchange Set Catalogue_ (pg. 23 in 5.1).
1. "ASCII" should be "TXT_UTF-8"
1. The offset for TXT_UTF-8 is ambiguous and is not well formed.
    * It appears to specify a character offset (the n'th character in the file), but UTF-8 encodings may contain multi-byte characters.
    * It encodes an integer value in a text field.
        * Recommend that for consistency with the other formats that an appropriate text pattern is provided instead of an offset.
    * If the offset value is retained, clarify that the value is a byte offset, not a character offset.

**Comment by rmalyankar** [comment]
Recommend prohibiting the use of _fileLocator_ with TXT_UTF-8 files.

**Comment by MikusRL** [comment]
Added in redline proposal to #159

**Comment by MikusRL** [comment]
@DavidGrant-NIWC Do you think that with the latest redlines for the S-101 v1.4.0 in the issue #159 this is now solved and can be considered to be closed? 

FYI @JeffWootton

**Comment by MikusRL** [comment]
@JeffWootton Can you please update the above finding? Thanks.

**Comment by JeffWootton** [comment]
@MikusRL  change has been applied in the DCEG. Consider this issue can now be closed.
