### ISSUE TITLE
Management of 'ENC Support Files' - DCEG Guidance & S-164 Test

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S-101-Documentation-and-FC#163]
According to S-100 Part 17 (17-4.3; 17-4.3.1 & 17-4.3.2) it is possible for S-101 producers to release an Exchange Set containing a new version of an existing 'ENC Support File' (most likely TXT and TIFF), outside an ENC update, when this file is already referenced by one or more published S-101 cells. ECDIS will then ensure the latest version of the file is presented to mariners upon pick report on any ENC features containing that file name in the sub-attribute **fileReference**. For this to work in practice, the ENC producer must populate specific values in some attributes of the corresponding S100_SupportFileDiscoveryMetadata:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70189016/8af1b309-e701-4d84-8858-c9e4125551d4)
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70189016/755b1f1e-abbb-41d8-8547-4930d198c012)

This new option, not previously available in S-57, can be of great help to producers as it would avoid releasing multiple ENC updates when they need to update the wording/image of an existing ENC Support File that is already referenced by multiple products that are in the market.

The AHO believes the DCEG is lacking guidance on 'how to' perform this encoding activity in order to guarantee ECDIS expected performance. Currently, S-98 does not describe this functionality in detail and the only information available seems to exist in S-100 itself.

A new S-164 test should be created to verify appropriate file management by ECDIS.

**Comment by kusala9** [comment]
Agree S-98 could better describe the support file mechanism better. raised https://github.com/iho-ohi/98-interoperability/issues/49 in S-98 to track this. S-164 has tests for support files but they will need enhancement to deal with all the different test cases. I will raise another issue for that and reference here.

**Comment by kusala9** [comment]
https://github.com/iho-ohi/S-164-Sub-Group/issues/87

**Comment by MikusRL** [comment]
I have updated the S-101 PS and DCEG texts regarding the Support file production and some expected management aspects as we discussed in the Support File TG VTC catch-ups, and have uploaded redlines for those texts based on the clean v.1.3.0 documents in the GitHub Issue #159 . Please review those and comment if feel that this still have not covered the expected clarifications on Support files and ENC Support files in particular. 
Looking now after finished those, there might be a chance that the detailed usecases from the PS could be moved to the DCEG. Opinions?
Of course the proposed redlines would be good to match the S-98. And from both of those to create a proposal for the clarifications/updates to S-100 v.6.0.0 regarding the Support files and their management.

**Comment by alvarosanuy** [comment]
Thanks @MikusRL  - Support the proposed changes and I look forward at having the capacity (we got Caris HPD 5.0.2 installed today - need to check performance) to create the exchange set **and** updating the corresponding S100_SupportFileDiscoveryMetadata fields and then test the overall pick report behavior in NIWC's shore ECDIS.

**Comment by MikusRL** [comment]
@JeffWootton To my understanding, the Alvaro raised concern is possible with the current wording of the S-101PS, and, after the S-101PT13 meeting, based on the @kusala9 comments and new issues raised for S-98 and S-164, this issue can be considered to be closed. 
Do you agree @alvarosanuy ?

**Comment by alvarosanuy** [comment]
> Do you agree @alvarosanuy ?

All good, thanks.

**Comment by JeffWootton** [comment]
To be addressed in S-98 and S-164 (new GitHub Issues created in those repositories).

Close issue.
