### ISSUE TITLE
DCEG Hierarchy of metadata - QualityOfNonBathymetricData

### ISSUE THREAD

**Issue by FrankHippmann** [iho-ohi/S-101-Documentation-and-FC#170]
In the table presented in DCEG 3.3 there is the row:

**Quality of Non-Bathymetric Data
orientation
orientation**

Should **orientation** be **orientationUncertainty**?

**Comment by JeffWootton** [comment]
Agree that this should be `orientationUncertainty`.

After discussion with S-101PT Chair 27/08/24, it was agreed to apply this change for S-101 Edition 1.5.0.

Close Issue pending any further feedback.
