### ISSUE TITLE
Multiplicity of Category of Dolphin

### ISSUE THREAD

**Issue by HermanSchouten** [iho-ohi/S-101-Documentation-and-FC#171]
Assisting with a NL proposal for S-131 project team, I noticed a mismatch between this and S-101 DCEG.
Combined Breasting and mooring dolphins exist in the real world and will be proposed within S-131 PT as new symbol.
Although the symbols in S-101 will not differ from S-57/S-52, it would be beneficial to be able to encode a combined Breasting and mooring dolphin in S-101, for the purpose of harmonization between the standards and products (S-101/ S-131). 
This can be facilitated by changing the Multiplicity to [1,*]

![image](https://github.com/user-attachments/assets/f56ec8c8-ba34-4089-a2d4-6b17c52bc1d0)

**Comment by JeffWootton** [comment]
Tend to agree with this proposed change. A use case has been put forward that indicates that a dolphin can serve more than one purpose.

**Comment by JeffWootton** [comment]
After discussion with S-101PT Chair 27/08/24, it was agreed to apply this change for S-101 Edition 1.5.0.

Close Issue pending any further feedback.

**Comment by mikan66** [comment]
![image](https://github.com/user-attachments/assets/98576000-fc91-4053-93a7-c8ff0b16546f)

**Comment by JeffWootton** [comment]
I think the preference would be to only have a single symbol portrayed rather than multiple symbols representing a single real-world feature displaying on top of each other.

Has this been resolved?

**Comment by HermanSchouten** [comment]
Agree, the preference would be to only have a single symbol portrayed.  
If category of Dolphin contains  deviation dolphin (2), a deviation dolphin should be portrayed. Even in cases where it is combined with other values 1,3 or 4.
