### ISSUE TITLE
Deep water route covered by Dredged areas.

### ISSUE THREAD

**Issue by HermanSchouten** [iho-ohi/S-101-Documentation-and-FC#172]
**DCEG vs 1.4.0:** States:
15.14.1	Deep Water route parts (see S-4 – B-435; B-435.3 and B-436.3)
Remarks:
•	The route **must** be covered by Depth Area features. 
--------------------------------------------------

Dredged Areas should also be allowed, this is quite common in NL. 

![image](https://github.com/user-attachments/assets/32f33d25-72d5-4b3a-96b4-4f7a035fe301)

**Comment by KlasOstergren-SMA** [comment]
I support the proposal. I cannot see why a deep water route cannot be in a dredged area. 
Validation check S101_Dev2141, which is equal to S-58 1692, already accept dredged areas:
`For each DeepWaterRoutePart which is not COVERED_BY the combined coverage of DepthArea and DredgedArea features.`

**Comment by JeffWootton** [comment]
After discussion with S-101PT Chair 27/08/24, it was agreed to apply this change for S-101 Edition 1.5.0.

Close Issue pending any further feedback.
