### ISSUE TITLE
Should attribute information be mandatory for MarinePollutionRegulationsArea?

### ISSUE THREAD

**Issue by FrankHippmann** [iho-ohi/S-101-Documentation-and-FC#177]
DCEG 16.28.1 Marine pollution regulations area states:

> A short summary of the regulation and a reference to the publication containing the regulation must be included using the complex attribute **information** (see clause 2.4.6).

There appears to be an inconsistency, since according to the FC, **information** is not mandatory for **MarinePollutionRegulationsArea**. 

See also validation check S101_Dev4091.

**Comment by JeffWootton** [comment]
The `information` complex attribute is conditionally mandatory for `MarinePollutionRegulationsArea` - only not required where it is associated to a `NauticalInformation` information feature, for which at least one of `information` or `pictorialRepresentation` is required. It is not expected that `pictorialRepresentation` would be used for `NauticalInformation` associated to `MarinePollutionRegulationsArea`, so it can be considered that `information` is mandatory "by default".

After discussion with S-101PT Chair 27/08/24, it was agreed not to apply this change for S-101 Edition 1.5.0.

Close Issue pending any further feedback.
