### ISSUE TITLE
DCEG 3.5 Data Coverage: Display scale comparison operators are contradictory.

### ISSUE THREAD

**Issue by FrankHippmann** [iho-ohi/S-101-Documentation-and-FC#178]
> maximum display scale ≤ optimum display scale < minimum display scale

contradicts

> minimum display scale ≥ optimum display scale > maximum display scale

Is the second equation supposed to be:

> minimum display scale > optimum display scale ≥ maximum display scale

3.5.1 states:

> **maximum display scale** must be a smaller value than/equal to **optimum display scale** which must be a smaller value than **minimum display scale**.

This would be consistent with:

> maximum display scale ≤ optimum display scale < minimum display scale

and

> minimum display scale > optimum display scale ≥ maximum display scale

**Comment by JeffWootton** [comment]
After discussion with S-101PT Chair 27/08/24, it was agreed to apply this change for S-101 Edition 1.5.0.

Close Issue pending any further feedback.
