### ISSUE TITLE
Offshore Production Area - Tank Farm

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-101-Documentation-and-FC#18]
Within the DCEG 1.0.2 at 14.6 the feature Offshore Production Area carries the simple attribute Category of Offshore Production Area. 

Although most values of this attribute seem logical value 4 Tank Farm does not seem logical as an offshore feature, clearly onshore it is logical. I propose removing the value of Tank Farm for Offshore Production Area based on a check of the number of encoded instances. As a consequence of this change the values of Product on this feature may also need to be removed with values 1 and 2 (oil/gas) being removed.

**Comment by alvarosanuy** [comment]
Unless somebody can produce  a valid use case, I support removing the following attribute values from the feature **OffshoreProductionArea**:

**categoryOfOffshoreProductionArea**= 4 (tank farm)
**product**=1 (oil) & 2 (gas)

**Comment by LeoKuzmin** [comment]
This proposal looks strange. There are many areas of oil / gas production on the sea, where there are additional storage facilities, tanks. The first thing that comes to mind is the "Oil Stones" area near Baku in the Caspian Sea, which is completely built on piles and has huge oil storage facilities. For small examples:
![image](https://user-images.githubusercontent.com/106175259/191968581-e22a243d-60b6-44dd-93ae-2d24d924081c.png)
I assume that there are such storage facilities off the coast of Norway.

**Comment by alvarosanuy** [comment]
> This proposal looks strange. There are many areas of oil / gas production on the sea, where there are additional storage facilities, tanks. The first thing that comes to mind is the "Oil Stones" area near Baku in the Caspian Sea, which is completely built on piles and has huge oil storage facilities. For small examples: ![image](https://user-images.githubusercontent.com/106175259/191968581-e22a243d-60b6-44dd-93ae-2d24d924081c.png) I assume that there are such storage facilities off the coast of Norway.

The picture shows an area where different activities occur at the same time (extraction, transference, storage). The whole area (minimum bounding polygon) should be encoded as an **OffshoreproductionArea** but, I think, we need a new category to describe the general purpose of the area. We can't say that the **categoryOfOffshoreProductionArea** for what we see in the picture is a Tank Farm.
For me, the area is an offshore oil/gas production area. It seems we may need a new category value (7); it can be called either 'oil/gas farm' (BUT we should then remove **product**=1 & 2 as the production area name is self explanatory) or 'Fossil Fuels farm' and retain oil and gas as valid **product** values. I keep using the term 'farm' as, for me, it describes the location where a number of activities occur (from extraction to storage).

**Comment by LeoKuzmin** [comment]
Main purpose of my message was we don't have to remove the 4(tank farm) value of categoryOfOffshoreProductionArea. 
As regard the picture. The current area on the large scale chart is encoded as separated features: Offshore platforms, Shoreline construction (open wharf)  and Offshore production area (tank farm) and etc. 
As regards a general term for the offshore production area, we don't need a new value since there is the 5th value of the category: Seabed Material Extraction Area. It also implies the extraction of products from under seabed.

**Comment by JeffWootton** [comment]
@LeoKuzmin has presented what is, in my opinion, a valid use case for retention of this value of categoryofOffshoreProductionArea and related product attribute, and I recall that there was also a further use case put forward when the value was first proposed for inclusion in S-101. I also agree that the generic term "seabed material extraction area" satisfactorily covers the suggestion put forward by @alvarosanuy. 

Close issue.
