### ISSUE TITLE
Minimum Display Scale and dataset display

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#19]
This refers to § 4.6 of the PS.
When the SENC does not contain a dataset at a smaller scale than the Mariner's selected viewing scale, I suggest allowing the display of the smaller Min DS dataset down to a zoom factor 0.5.
This seems reasonable in terms of negative zoom limit and has some consistency with an overscale indication that is triggered from a zoom factor 2 from the max DS.

**Comment by alvarosanuy** [comment]
Refer to AU comments to S101 PS 1.1.0

**Comment by Christian-Shom** [comment]
Comments on AUS input:

- What is the use case for "_gaps between minimum display scale and maximum display scale between overlapping datasets_"? Doesn't that mean that the ENC portfolio is (temporarily?) incomplete? Alvaro, thanks if you can provide an example.
- In such cases, isn't it better to zoom out on the larger scale until we reach MSVS=smaller scale Max DS/2 (overscale limit)?

**Comment by alvarosanuy** [comment]
> Comments on AUS input:
> 
> * What is the use case for "_gaps between minimum display scale and maximum display scale between overlapping datasets_"? Doesn't that mean that the ENC portfolio is (temporarily?) incomplete? Alvaro, thanks if you can provide an example.

We have many examples where minDS for a dataset is, for example, 22000 and the next best scale overlapping dataset maxDS=90000. We do not create a dataset to cover the gap, we encode SCAMIN in the cell having minDS=22000 in a way it provides a clear and safe picture to the mariner until MSVS hits the maxDS of the smaller scale overlapping ENC.

> * In such cases, isn't it better to zoom out on the larger scale until we reach MSVS=smaller scale Max DS/2 (overscale limit)?

Current guidance in PS 1.1.0 states:
_'When the mariner’s selected viewing scale (MSVS) is smaller than the value indicated by minimum display scale, features within the Data Coverage feature are not displayed, except where ....'_ 

Our proposal wants to ensure the data continues being displayed when MSVS is smaller than minDS (i.e 22000). It is better to continue displaying the data in the larger scale dataset until we reach a point where the smaller scale dataset can be shown without overscaling it.

**Comment by Christian-Shom** [comment]
Sub-Group meeting 2022-10-19 agreed on (for edition 1.1.0 testing):

- When no smaller scale dataset is available, allow zoom out so that the dataset will continue to display in order to ‘fill’ the ECDIS window;
- In case of a scale range gap between 2 successive datasets, the larger scale dataset will be displayed until the viewing scale is equal to the Maximum Display Scale of the smaller scale dataset.
Note: Klas's post-meeting comment to be considered: "In such cases, why not set the minDS (of the larger scale dataset) to the same value as maxDS of the next smaller scale ENC."

**Comment by alvarosanuy** [comment]
> > We have many examples where minDS for a dataset is, for example, 22000 and the next best scale overlapping dataset maxDS=90000. We do not create a dataset to cover the gap, we encode SCAMIN in the cell having minDS=22000 in a way it provides a clear and safe picture to the mariner until MSVS hits the maxDS of the smaller scale overlapping ENC.
> 
> Just for my understanding, maybe I have missed something. Is there a reason why you cannot set the minDS to the same value as maxDS of the next smaller scale ENC (in this case 90000)? If you assign SCAMIN values to provide a clear and safe picture of the dataset, I would say that the intended display scale range is between the maxDS of this ENC and all the way out to the maxDS of the next smaller scale ENC.

@KlasOstergren-SMA - That would work fine if the larger scale dataset is fully covered by only one smaller scale product. What if there are 2 or more overlapping, smaller scale datasets, each of them with a different maxDS (e.g. 90000, 180000, 350000)?
We wouldn't be able to allocate the larger scale dataset a unique minDS value that 'closes the gap' with all the overlapping ENCs as you propose.
I think that your proposal is a good recommendation for HOs when planning their migration to S101 but, when not possible to follow, the loading/unloading algorithm has to be designed in a way it gives priority to 'under scaling' (not 'over scaling').

**Comment by KlasOstergren-SMA** [comment]
> @KlasOstergren-SMA - That would work fine if the larger scale dataset is fully covered by only one smaller scale product. What if there are 2 or more overlapping, smaller scale datasets, each of them with a different maxDS (e.g. 90000, 180000, 350000)? We wouldn't be able to allocate the larger scale dataset a unique minDS value that 'closes the gap' with all the overlapping ENCs as you propose. I think that your proposal is a good recommendation for HOs when planning their migration to S101 but, when not possible to follow, the loading/unloading algorithm has to be designed in a way it gives priority to 'under scaling' (not 'over scaling').
@alvarosanuy I understand your use case and fully agree that the loading/unloading needs to take this cases into account when it's not possible to set minDS = maxDS of the overlapping ENC. What minDS do you set in this cases? The maxDS from the overlapping ENC with the largest scale (e.g. 22000 if you have overlapping ENC's with maxDS 22000, 90000 and 180000)?

**Comment by JeffWootton** [comment]
Agree that the last response from @alvarosanuy needs to be discussed and resolved in the Main document, as this scenario is not currently covered. As I see it, there are two solutions:
1) Set minimumDisplayScale for the larger scale dataset to the largest maximumDisplayScale of any overlapping smaller scale datasets. The ECDIS would then need to apply the convention specified in clause 4.6, 3rd paragraph, of the S-101 Main document (Ed. 1.1.0) - "When the mariner’s selected viewing scale (MSVS) is smaller than the value indicated by **minimum display scale**, features within the **Data Coverage** feature are not displayed, except where the System Database does not contain a dataset covering the area at a smaller scale, in which case the dataset will be continuously displayed.".
2) Set minimumDisplayScale for the larger scale dataset to the smallest maximumDisplayScale of any overlapping smaller scale datasets. This however would break the rule at clause 4.6, 2nd paragraph, of the S-101 Main document (Ed. 1.1.0) - "There must not be overlapping scale ranges between datasets covering the same geographical area.". Tis would then need to be included as an additional "exception" along with the "5 metre overlap" exception.

To be discussed at the next DCEG Sub-Group meeting.

**Comment by JeffWootton** [comment]
To be resolved by discussions associated with Issue #52.  Close Issue.

**Comment by RichardCoyles** [comment]
To understand @alvarosanuy scenario, my diagram may contribute to discussion (or not). I feel the overlaps in position 2 would interfere with data loading:



![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/108347351/3bda3715-92de-462a-9281-82bc85401088)
