### ISSUE TITLE
Issue naming

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#2]
Recommend using labels rather than a naming convention to identify the sub-group(s) associated with each particular issue. This has the following advantages:
* is standard practice on GitHub
* is easier to read, and can be used to sort and filter issues
* multiple labels can be assigned so that discussions do not have to be duplicated

The _Labels_ button can be used to add/edit the labels available in the repository:
![image](https://user-images.githubusercontent.com/62906211/118631633-b1764a00-b79d-11eb-9c10-7739de3e0ed5.png)

The Labels button within an issue can be used to add/edit the labels associated with each issue:
![image](https://user-images.githubusercontent.com/62906211/118632317-4aa56080-b79e-11eb-9181-3b59cc90c513.png)

Here's an example issue from the S-101 PC GitHub with an "enhancement" label:
![image](https://user-images.githubusercontent.com/62906211/118632566-8d673880-b79e-11eb-90b1-63f8a52e0fd7.png)

**Comment by Christian-Shom** [comment]
Thanks Dave for your input (I'm quite new on the Github!)
