### ISSUE TITLE
Buoy New Danger Marking

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-101-Documentation-and-FC#20]
In S-101 1.0.2 the feature Buoy Emergency Wreck Marking was changed to Buoy New Danger Marking. 

From discussions with IALA the New Danger Marking concept is broader and not directly equivalent. 

It is therefore proposed to revert to Buoy emergency Wreck Marking and apply this change for FC 1.1.0. 

To note consequential impact on the Feature Catalogue, Portrayal Catalogue and Validation Checks.

**Comment by JeffWootton** [comment]
Changes have been made throughout the DCEG for draft Edition 1.1.0 to revert back to BuoyEmergencyWreckMarking.  To be reviewed at the DCEG Sub-Group meeting October 2022.

**Comment by alvarosanuy** [comment]
Change is supported.

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  2.2, 2.4.3, 2.5.9, 18.1, 18.3, 18.3.1.1, 20.5.1, 20.6

Points to Note:
-  Advice has been received officially from IALA that the feature BuoyNewDangerMarking should be changed (back) to BuoyEmergencyWreckMarking.
-  Changes made throughout the DCEG to reflect this renaming.
-  Recommend Sub-Group members check the resultant changes and report any issues.

Discussion/Decision:
-  It was reported that changes had been made throughout the DCEG to reflect the change of name of the BuoyNewDangerMarking feature to BuoyEmergencyWreckMarking.  Sub-Group members were requested to report any required changes that have been missed to IHO Sec at the earliest opportunity.

**Action:**
**-  Sub-Group members to report any changes resulting on the change of name of BuoyNewDangerMarking feature to BuoyEmergencyWreckMarking to IHO Sec at earliest opportunity (All).  [Ongoing]**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**

All resultant DCEG changes approved at S-101PT9 (November 2022).
