### ISSUE TITLE
Value of Local Magnetic Anomaly

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#21]
Refer to S-101 Portrayal Sub-WG issue #102 at https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/102.

Suggest that valueOfLocalMagneticAnomaly can be remodeled as a complex [1..2] with sub-attributes magneticAnomalyValue [1..1] and referenceDirection [0..1] (enumerate with allowable values east and west).  Would require some complex portrayal rules but I think this will work:
- If only a single instance of valueOfLocalMagneticAnomaly is encoded with no populated value for referenceDirection, this means that the value in magneticAnomalyValue is the same both E and W;
- If only a single instance of valueOfLocalMagneticAnomaly is encoded with a populated value for referenceDirection, this means that the value in magneticAnomalyValue is only in the indicated direction E or W;
- If two instances of valueOfLocalMagneticAnomaly are encoded referenceDirection becomes mandatory for both, thus indicating that magneticAnomalyValue is the different for E and W.

I think this satisfies all the described scenario's in S-4 clause B-274.1.

For S-4 clause B-274.2, suggest that the encoding guidance is that valueOfLocalMagneticAnomaly/magneticAnomalyValue should be populated as empty [null] and an associated instance of NauticalInformation is encoded for the note.

**Comment by JeffWootton** [comment]
Here is an excerpt of clause 4.2 from the DCEG representing the above modelling and associated guidance:
[DCEG Clause 4.2.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/9575435/DCEG.Clause.4.2.docx)

**Comment by alvarosanuy** [comment]
**Editorial comment**: I think the symbol **†** should be moved to the following paragraph.

**Comment by Christian-Shom** [comment]
Agree with the proposed new modelling and guidance.

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  4.2, 27.118, 27.119

Points to Note:
-  Note separate document for meeting (no change as yet made to DCEG).  Show new version.
-  Proposal is to replace the complex attribute valueOfLocalMagneticAnomaly, sub-attributes magneticAnomalyVaueMaximum and magneticAnomalyVaueMinimum, with new sub-attributes magneticAnomalyVaue and referenceDirection.  The accompanying new encoding guidance covers all options for representing local magnetic anomalies on charts as defined in S-4.
-  Note that amendments have been applied to the posted (GitHub) document to account for Alvaro’s comment.
-  If accepted, question is the code values for referenceDirection.

Discussion/Decision:
-  There were no objections raised as to the proposed remodelling.  Sub-Group member feedback in general was that the revised modelling would solve the portrayal issue reported by the Portrayal Sub-Group.
-  There was some discussion on the referenceDirection sub-attribute name, with the suggestion that the already registered enumerate type attribute cardinalDirection is used instead.  Noting that the term “Reference Direction is an IHO Hydrographic Dictionary term and as such registered in the Concept Register, it was agreed to stay with referenceDirection.  However it was agreed that the allowable enumerate code values (east and west) should be aligned with the values registered for cardinalDirection (5 and 13 respectively).

**Action:**
**-  Amend DCEG to reflect change of modelling for the complex attribute valueOfLocalMagneticAnomaly as proposed (IHO Sec).  [Complete].**
**-  Corresponding proposals to be submitted to Concept Register (IHO Sec).  [Complete]**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**

All resultant DCEG changes approved at S-101PT9 (November 2022).
