### ISSUE TITLE
Encoding Synthetic AIS Aids to Navigation

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#23]
IALA have reported that there is a requirement to indicate in ENCs where an apparent AIS signal is being transmitted from a physical AIS aid to navigation from a remote location (such as an AIS Base station).

I have included some draft remodelling and accompanying guidance for the PhysicalAISAidToNavigation feature (DCEG clause 21.3) to include a new Boolean type attribute syntheticAISAisToNavigation.  A description of this new proposed attribute is also included in the draft DCEG at new clause 27.165.  The draft will be circulated for discussion at the October DCEG Sub-Group meeting.

![image](https://user-images.githubusercontent.com/70211773/190417832-e454f1d2-1cf9-4bbf-b41a-d76bf6b11f18.png)

**Comment by MikusRL** [comment]
> IALA have reported that there is a requirement to indicate in ENCs where an apparent AIS signal is being transmitted from a physical AIS aid to navigation from a remote location (such as an AIS Base station).

Hi Jeff, I trust you meant to say "... where an apparent AIS signal is being transmitted **to** a **physical aid** to navigation from a remote location, **making it to look like a physical AIS AtoN on the ECDIS screen**..." Am I correct? 

In the DCEG screenshot you have captured it correctly.

**Comment by JeffWootton** [comment]
Thanks Mikus and apologies - you are correct.  This proposals is for synthetic AIS aids to navigation.

**Comment by alvarosanuy** [comment]
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/70

**Comment by GuttormTomren** [comment]
Here is the latest info from IALA A-126:
4.2.2. SYNTHETIC AIS ATON 
AtoN that physically exists, but which is transmitted from a geographically separated AIS AtoN station (base station 
or standalone unit) is a Synthetic Predicted AIS AtoN. It is displayed as a solid line diamond with crossed lines 
centred at the reported position of the AtoN. 
IEC62320-2 states that “for Synthetic AIS AtoN messages, the repeat indicator field shall be set to 1, 2, or 3 to signify 
that the message is transmitted from a position other than that provided in the message”. 

Thanks to Jeff for adding this issue to GitHUB. 
IALA supports having text "S-AIS" supporting the solid diamond symbol.
