### ISSUE TITLE
Quality of Bathymetric Data and Spatial Accuracy - resolution of modelling alternatives.

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#24]
In DCEG Edition 1.0.2 there remains two alternatives for the encoding of vertical and horizontal position uncertainty taking into account degradation of uncertainty over time.  A preferred option should be agreed and included for implementation in S-101 Edition 1.1.0.

Alternatively, both options my be retained for Edition 1.1.0 to enable a more informed decision through implementation and testing of both options, however this would definitely require a further 1.x.0 version of S-101 for full implementation and testing of the preferred option in the Feature Catalogue before the operational Edition 2.0.0 release.

To assist with deliberation and discussion, the relevant clauses (3.7 and 24.5) of the draft DCEG Edition 1.1.0 are included in the attachment:
[DCEG Clauses 3.7 and 24.5.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/9583679/DCEG.Clauses.3.7.and.24.5.docx)

The sections of each clause relevant to the alternate options are indicated in the document in green text.

**Comment by DavidGrant-NIWC** [comment]
![image](https://user-images.githubusercontent.com/62906211/197049269-966ae36f-720e-4078-9c48-062a4f669bd2.png)

This should be updated. The dates must form a continuous interval with no overlaps.

|#|Date Start|Date End|Remarks|
|:---:|:---:|:---:|:---|
|1||20211231|Beginning of time through the last second of 2021|
|2|20220101|20221231|Every second of 2022
|3|20230101||First second of 2023 until the end of time|

**Comment by JeffWootton** [comment]
**From DCEG Sub-Group meeting 3 Record:**

Points to Note:
-  Note separate document for meeting (no change as yet made to DCEG).
-  There remain 2 methods for encoding spatial quality meta information in S-101:
-  Using zoneOfConfidence complex attribute on QualityOfBathymetricData; and
-  Using spatialAccuracy complex attribute on SpatialQuality and mandatory SpatialAssociation association to QualityOfBathymetricData.
-  A preferred method needs to be decided on before Edition 2.0.0.  Do we retain the 2 methods for 1.1.0?

Discussion:
-  While the general opinion of the meeting was that the better of the 2 encoding options is the retention of the encoding of the horizontal and vertical uncertainties on the QualityOfBathymetricData feature, it was agreed that, due to lack of test data and testing opportunities, both options should be retained for S-101 Edition 1.1.0 so as to allow testing of both options to take place.
-  Concerns were raised that there could be portrayal issues with the option of binding the horizontal and vertical uncertainties to the SpatialQuality information type (refer to Issue #25).

**Decision/Action:**
**-  Keep Issue open for contributors to include additional comments/observations and as a mechanism for posting/discussing testing results (All).  [Ongoing]**
**-  Bring the requirement for the testing of both options for the encoding of QualityOfBathymetricData to the attention of the Test Dataset Sub-Group for development of appropriate test data (IHO Sec).**

**Comment by JeffWootton** [comment]
The DCEG Sub-Group Action to bring to the attention of the Test Datasets Sub-Group has been completed.

No further comments received since S-101PT9. Further related discussion on meta features in general at S-101PT10 resulted in Action S-101PT10-25 and a paper will be submitted to S-101PT11 covering this Action. Close Issue pending discussions at S-101PT11.
