### ISSUE TITLE
Reported Anchorages

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#28]
Refer to S-101 Portrayal issue #72: (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/72)

Outcome of Portrayal Sub-Group meeting July 2022:
3.  Jeff - DCEG SubWG to discuss modelling or new guidance to prevent the use of categoryOfAnchorage=15 (reported anchorage) in AnchorageArea features of geometric primitive Surface.

DCEG Action:  Draft new bullet for consideration of the DCEG Sub-Group:
![image](https://user-images.githubusercontent.com/70211773/191204858-d107bfee-37c2-4000-bc03-63ef197a8899.png)

**Comment by KlasOstergren-SMA** [comment]
I support this proposal

**Comment by TomRichardson6** [comment]
Support this change

**Comment by Christian-Shom** [comment]
I can't see the distinction (for the encoder) between the features described in bullets 3 and 4. Shouldn't they be merged?

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  16.3.1

Points to Note:
-  Portrayal Sub-Group has developed a new symbol for reported anchorage, however it is only intended for use as a point feature.
-  Proposal is to amend guidance in the DCEG to mandate that reported anchorages must only be encoded using the point primitive.
-  Note support from Tom and Klas without comment.

Discussion/Decision:
-  It was questioned whether there is any difference between a recommended anchorage and a reported anchorage.  It was agreed that there was sufficient distinction described in the Remarks at clause 16.3.1 to support the retention of reported anchorages.
-  The proposal was supported by the Sub-Group.

**Action:**
**-  Amend DCEG clause 16.3.1 to include a new Remarks bullet specifying that reported anchorages are to be encoded using point primitive only (IHO Sec).  [Complete]**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**
