### ISSUE TITLE
Dumping Ground - Encoding Guidance

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#33]
Refer to S-101 Portrayal issue #44: (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/44)

Outcome of Portrayal Sub-Group meeting July 2022:
1. Pass this Issue to the DCEG SubWG to review existing encoding guidance regarding best practices for the encoding of DumpingGround when post-dredged surveys are not submitted to HOs.
2. Leave this issue open for member states to comment on:
-  The benefit of including DumpingGround in the A&I catalogue (Indication - Yellow highlight).
-  Should categoryOfDumpingGround=5 (spoil ground) trigger an Indication? If depths are updated post dredging this may not be necessary and, If they are not, DCEG currently recommends replacing the feature with UNSARE !
-  The benefit of having its own symbology in CHGRD colour instead of Magenta. An option could be not to run this feature through RESARE04 but retain Symbolised and Plain (Point & Surface) symbology as per S-52 (DMPGRD) but in CHGRD colour instead???

The Portrayal issue is most relevant for spoil grounds.  Having given this some consideration, some changes have been applied at DCEG clause 16.6 for consideration of the DCEG Sub-Group:

![image](https://user-images.githubusercontent.com/70211773/191501573-3f3f36f7-5782-4bcc-a844-e2007879f902.png)

Some points to note:
- The introductory paragraph at clause 16.6.2 has been expanded to emphasize that the ENC should be updated so as to include the latest survey information covering the spoil ground where possible.
- The former 3rd Remarks bullet for clause 16.6.1 has been moved to 16.6.2 and expanded to include alternate encoding guidance to downgrade the underlying QualityOfBathymetricData feature.  Consider that the option to encode as UnsurveyedArea remains valid.
- As mentioned in Portrayal issue #44, the level of accuracy to which the depth detail within a spoil ground can be encoded in an ENC is dependent on the frequency that the spoil ground is surveyed (for example regular post-dumping surveys) and the capability for the Producing Authority to receive this survey information and subsequently update the ENC.  Taking into consideration these factors the level of accuracy to which an encoded spoil ground can be encoded in ENCs may differ considerably, and this should be taken into consideration in deliberations.  For example, encoding guidance and the resultant performance of the ENC in the ECDIS should not be such that the encoding will set off multiple alarms to identify the same potential hazard to navigation regardless of the accuracy to which the spoil ground has been encoded.

**Comment by Christian-Shom** [comment]
- Having various encoding possibilities is probably the best solution (apart from global ENC consistency) for the different views that HOs may have on this subject.
- In terms of QualityOfBathymetricData feature over a DumpingGround, is it reasonable to copy/paste the survey characteristics, as (very) shoaler depths are likely to exist in a very short term? Agree the DCEG should provide guidance on this (i.e. How to degrade the QualityOfBathymetricData feature).
