### ISSUE TITLE
Cranes - Requirement for Curve Geometry

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#34]
Refer to S-101 Portrayal issue #75: (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/75)

Outcome of Portrayal Sub-Group meeting July 2022:
Note that DCEG subWG lead will investigate the existence of a use case for the encoding of Crane features using Curves. DCEG 8.12 instructs to use a Railway feature to depict a Crane's track (!?). See DCEG extract below:

![image](https://user-images.githubusercontent.com/70211773/191513633-ed01a0a3-6e37-4046-90e4-408147644dd2.png)

Looking back through the records of the development of the DCEG, there is a record of a decision to include curve as a valid geometric primitive for the Crane feature for the initial DCEG Baseline release, however my comment against this as the DCEG Sub-Group lead at the time was that there was no record of discussion as to why this decision was made or any record of a use case to support the decision.  Guidance already exists in the DCEG as shown above to encode a Railway feature for the track along which a crane may positioned.

Suggest that unless a use case is presented to support the retention of curve as an allowable primitive for Cranes, this option is removed from the DCEG.

**Comment by Christian-Shom** [comment]
Agree with keeping the current guidance (encode Railway feature along the track when needed).
Yet, it might be interesting to look at S-131 if Curve primitive is allowed for Cranes in order to avoid encoding redundant features as source data.

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  8.12

Points to Note:
-  Proposal is to remove curve as an allowable geometric primitive for the Crane feature.
-  Note already existing guidance for the encoding of the track for a sheerleg or travelling crane.
-  Unless use case is provided, recommend removal of curve.
-  Note Christian comment (approval of proposal?) with reference to S-131.

Discussion/Decision:
-  There was some discussion as to the track along which a sheerleg or travelling crane runs, with agreement that the current method of encoding a Railway feature to define the track is sufficient.  It was suggested that the relationship between the crane and the track could be further strengthened by defining a feature/feature association between them.
-  The question was raised as to whether curve primitive is allowable for cranes in S-131.  Jonathan greed to investigate and report back to the Sub-Group lead.

**Action:**
**-  Remove curve as an allowable geometric primitive for the Crane feature for DCEG Edition 1.1.0.  [Complete]**
**-  Investigate whether curve primitive is allowable for cranes in S-131 and report to Sub-Group lead (Jonathan).**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**
