### ISSUE TITLE
Information Area - Geometry

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#36]
Refer to S-101 Portrayal issue #76: (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/76)

Outcome of Portrayal Sub-Group meeting July 2022:
3. **Jeff** and **DCEG subWG** to review and update/fix the inconsistency (conflict) of guidance of curve encoding in the DCEG, as it allows the curve as a primitive, but recommends to create a thin area instead further in the last bullet point.

The inconsistency in the DCEG is the inclusion of curve as an allowable geometric primitive for the InformationArea feature (DCEG clause 16.11) and the conflicting Remarks 3rd bullet at clause 16.11.1:

![image](https://user-images.githubusercontent.com/70211773/191677590-3bd1e8e7-750f-4fe3-9c4f-192872472cc4.png)

Discussion points:
- Does a use case exist for curve to remain as an allowable geometric primitive for InformationArea?  If yes, retain curve as allowable geometry and remove Remarks 3rd bullet point.  If no, remove curve as allowable geometry.
- If the answer to the above question is no, should the Remarks 3rd bullet be retained to account for the possibility of very rare (unforseen) instances where line type information is required to be encoded?
- Item for comparison:  The feature CautionArea (DCEG clause 16.10) does not include curve as an allowable geometric primitive.  Further, there is no guidance for CautionArea for the encoding of a "very narrow area" to represent a line type in the ENC.

**Comment by Christian-Shom** [comment]
- Agree to align Information Area with Caution Area and remove curve as allowable geometry.
- Of the opinion to also remove guidance for the encoding of a "very narrow area".

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  16.11, 16.11.1

Points to Note:
-  Issue is inconsistency between the allowable geometric primitive curve for InformationArea and the Remarks 3rd bullet at clause 16.11.1.
-  Is there a use case for curve primitive?
-  Noting the comparison with encoding CTNARE for S-57 ENC, suggest that both the curve primitive is removed as an allowable geometric primitive for InformationArrea and the Remarks 3rd bullet is removed.

Discussion/Decision:
-  There were no use cases put forward for the retention of curve as an allowable geometric primitive for the feature InformationArea.  It was therefore approved to remove curve as an allowable geometric primitive.
-  Given the lack of any use case, it was further agreed to remove the encoding guidance related to the encoding of a “very narrow are” to define a “linear” InformationArea.  If a use case for linear InformationArea is put forward in the future, the preference will be to re-introduce curve as an allowable geometric primitive.

**Action:**
**-  Amend DCEG clause 16.11 to remove curve as an allowable geometric primitive for the feature InformationArea.  Remove Remarks 3rd bullet from clause 16.11.1 (IHO Sec).  [Complete]**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**
