### ISSUE TITLE
Minimum Berth Depth

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#39]
A new concept minimumBerthDepth has been accepted into the IHO GI Registry, Concept Register for use in the S-131 Product Specification, where it has been modelled as a simple attribute.

For the S-101 feature Berth (DCEG clause 8.13), the minimum depth at the berth is currently encoded using the attribute depthRangeMinimumValue.  It is proposed that the new attribute minimumBerthDepth replace the attribute depthRangeMinimumValue to encode the shoalest physical depth at the berth.

![image](https://user-images.githubusercontent.com/70211773/192723650-215585eb-49a4-4630-80d1-aee1510b4560.png)

![image](https://user-images.githubusercontent.com/70211773/192727688-63c700be-cb80-4aa7-befc-85b4ab16e506.png)

**Comment by TomRichardson6** [comment]
Support this change

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  8.13, 27.124 (new)

Points to Note:
-  Noting that a new concept minimumBerthDepth has been included in the IHO GI Registry for S-131, proposal is to adopt this to replace depthRangeMinimumValue for the Berth feature in S-101.
-  Suggest that this change better supports data consistency and interoperability.

Discussion/Decision:
-  The meeting agreed that the proposed change supports data consistency and interoperability.

**Action:**
**-  Amend DCEG to amend attribute depthRangeMinimumValue to minimumBerthDepth for Edition 1.1.0 (IHO Sec).  [Complete].**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**
