### ISSUE TITLE
Improvement of scale minimum

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#4]
Here after, a few condiderations (from document "Scales_Sub_Group_initial_document.pdf") to initiate discussions on scale minimum in S-101:
- All objects must be displayed at Maximum Display Scale (MaxDS)
- scale minimum values should (must?) be between MaxDS and MinDS
- scale minimum values could be different than the ones listed in DGEG Table 2.6 (there is a "must" in current version)
- Why not allowing scale minimum on some objects that belong to the Base Display (ex: Point Land Areas that touches the coastline when zooming out and contribute to screen clutter).

**Comment by Christian-Shom** [comment]
**Mail from Christian on 2021/06/25:**
scale minimum values are not mandatory in S-57 but are in the current DCEG (2.5.9 : scale minimum values used must be selected from the following list...).

I wonder why this has become mandatory.

My understanding is that even if the ENC is often displayed on the ECDIS at standard radar ranges, it can also be displayed at any scale. If scale minimum or SCAMIN is populated with a value that is not in the list, it will be implemented in the same manner by the ECDIS, comparing the encoded value with the Mariner selected viewing scale (MSVS). So I can't really see why values out of the list could not be used.

Shom is currently (actually for some time now) working on an improvement (refinement) of SCAMIN. The objective is to avoid (as much as possible) symbols overlap, whatever the MSVS. Typically (just an example), "as soon as" 2 obstructions overlap partially, a SCAMIN value is applied on the less significant (the one that has the bigger value for VASOU), so that the most significant object remains on the screen.
The idea is to avoid screen clutter and to see the objects disappearing more gradually than it is now.

This new policy will probably be implemented this year on our S-57 ENCs (first, at the occasion of new editions).

This said, you will understand that Shom is not in favour of mandating scale minimum values in S-101.

I'm happy to get your comments on this.

**Comment by Christian-Shom** [comment]
**Comment from Alvaro on 2021/06/28:**
My understanding is that, although currently OEMs are not enforced to have standardised MSVS, this is expected/planned for ‘pure’ S-100 ECDIS.

At the moment the majority of OEMs allow for standard radar ranges to be used as ‘viewing scales’ but in practice they all refer to slightly different numeric scale values.

The reality negatively impacts on the practical use of SCAMIN values by HOs as you will plan your transitions based on steps that mariners may not have available. This may cause, for example, features to remain visible when you don’t want or the other way around.

The mandatory values make sense only if S-100 ECDIS have a performance requirement to have the same display scale values available in the GUI. If this is not going to be implemented then we are back in square 1 and the visual performance of ENCs will continue being something that HOs won’t have full control of.

We may expend a lot of time planning the transitions between scales but many mariners will probably see something different on the screen ………

Hope it helps,

Alvaro

**Comment by Christian-Shom** [comment]
**Comment from Jonathan on 2021/06/28:**
 this is my understanding of the situation too. ECDIS don't have standardises MSVS, some only have discrete levels whilst others have a continuous (slider or selection). this causes a radical difference in appearance sometimes as S-52 doesn't define when data should be brought into view. The reason for the adoption of radar ranges is they are stanrdised so you know all ECDIS will at least support them. I have input to the S-98 Annex C discussions the points about viewing scales but I think it's one we should revisit as that document matures - it will define for many ECDIS how these scales are implemented. Alvaro is right - we can plan all we want, if standardisation isn't reflected in the viewing scales it loses a lot of its impact.

Another point to make is that if continous zoom scales were adopted by all OEMs then the S-57 case ( for dual fuel mode) would be fixed too. harmonising the loading strategies across DF mode will be a challenge too I think.

Jonathan.

**Comment by Christian-Shom** [comment]
**Comment from Tom R. on 2021/06/28:**
I do recall some analysis which compared scale levels in various ECDIS systems, but I can’t find it easily and it would be rather old.

Alvaro, does the Portrayal Sub-Group have this on its list of ECDIS Performance Requirements?

I currently see this whole aspect including display and loading as in a state of flux so I think more test and development is needed to achieve stability, then we should be able to make changes to the S-101 spec.

Of course, SHOM would be welcome to propose this formally as a change for S-101 1.1.0 through the current review period.  

Regards,
 
Tom

**Comment by Christian-Shom** [comment]
**Comment by Jeff on 2021/06/28:**
I agree with all the feedback that has been provided on this topic.  From a historical perspective, the mandated values for SCAMIN were introduced in a very early draft of the DCEG (probably about 10 years ago now - I have gone back to the first baseline draft in 2013 and the "must" is there).  In fact in the draft 0.0.1 of the DCEG the scaleMinimum (as well as maximumDisplayScale and minimumDisplayScale) attribute was an enumerated type with each enumerate code value corresponding to one of the values for scaleMinimum that are now included in DCEG table 2.6.  Personally I would have preferred to keep it this way as it guarantees greater control;  but the DCEG Sub-Group at the time considered that this would be too restrictive in regard to other S-100 based Product Specifications so the attribute was changed to integer type.

Regardless of the values to be used (again agreed on many years ago and based on the old "radar range display" introduced as guidance for S-57 ENCs), from a cartographic perspective there must be some relationship between display scale attributes populated by the encoder and the actual display scale of the information in ECDIS.  In my former life at the AHO, I maintained to our compilers that SCAMIN is the only truly cartographic attribute included in the S-57 ENC Product Specification as it provides an opportunity for the compiler to determine the optimum display content at certain display scales.  However this does not work if there is no minimum standard set of display scales that all ECDIS must use when the mariner zooms out or in.  For example, Australia has implemented that radar-range based compilation scales for their ENCs and has developed its SCAMIN policy based on these compilation scales.  One particular ECDIS, for features encoded with the value 21999 for SCAMIN, has these features appear only in overscale display when "stepping out" through the implemented display scale steps in the ECDIS; and at the next display scale step out the features do not appear on the screen because that display scale exceeds 1:21999.  However on some other ECDIS this scenario does not occur.  It is impossible for the cartographer to account for every possible ECDIS implementation when assigning SCAMIN - the hope is that by mandating the values to be used in S-101 ENCs the ECDIS the corresponding display scales will also be implemented as a minimum set of viewing scales (noting that there is no problem with including other "intermediate" display scales should they wish to do so).

Best Regards,

Jeff.

**Comment by MikusRL** [comment]
After discussion with Verena (LINZ NZ) regarding the bullet: 
"* scale minimum values should (must?) be between MaxDS and MinDS"
NZ would suggest for discussion, that the SCAMIN attribute to be considered as constant, once set value (in the case of source database - most likely already in the database). That would facilitate features consistent appearance and disappearance for the end user, and facilitate once encoded - used many times on many products, and consistently. We would like to learn, if there are possibility that the SCAMIN value can successfully be smaller than the MinDS as allowable value, and the feature still would be unloaded, if the datasets MinDS is reached and the dataset has to be unloaded. This way the production database would be independent of products - but in a way a consistent product in its own already - digital twin, if you like, but with an attribute attached for human readability of the database and generated out of that ENCs and charts (implemented cartography in the base). 
Whether the above in regards to SCAMIN is possible or not should not impact the discussion on what the ECDIS performance standard should include regarding end user zooming in ECDIS. Reading the above efforts reasonable seams that the zooming is smoother, the more control over features disappearing the HOs would have. The smoother the zooming might also overcome some of the issues regarding the different MaxDS and MinDS values the neighboring countries might have on the end users display (reasonable differences though only). 
And last but not least the smoother zooming might also help the idea of data rendered in much greater area than the screen actually portrays for the sake of being able to portray on screen for example sector lines and arcs, even if the light feature itself is still not within the display coverage. I acknowledge, that this requires much more resources on rendering the data, but I am also pretty sure that technology and hardware is very much capable of that already. This then would be necesary to define also in this minimum ECDIS requirement, so all official ECDIS would be capable of doing that. This last bit though might be a separate issue to discuss on its own. Happy to hear comments.

**Comment by JeffWootton** [comment]
No comment on this GitHub issue since June 2021. Consider that this may have been overtaken by events (S-101PT discussions, publication of S-101 Edition 1.1.0. Issue closed bending any further requirement.
