### ISSUE TITLE
Encoding of Dates

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#40]
S-100 Edition 5.0.0, clause 3-8.3 is as follows:

![image](https://user-images.githubusercontent.com/70211773/192286615-01fbed01-b0df-47d5-b8d7-1a060273a19d.png)

The "inclusiveness" of encoded date ranges as specified in S-100 clause 3-8.3 is not described currently in the DCEG.  Further, this "inclusiveness" is not reflected in the current DCEG guidance at clause 2.4.8.1 for the encoding of the end date of the "last day of February" to take into account leap years.  As can be seen above, the encoding of the "last day of February" as an end date of _----02--_ resolves this issue (noting, however, that there is still no simple solution for the encoding of the start date of a range as the "last day in February").  It is suggested therefore that DCEG clauses 2.4.8 and 2.4.8.1 are amended as follows:

![image](https://user-images.githubusercontent.com/70211773/192289787-4c5b0e90-d63a-4264-8de7-b3bf6479d620.png)

Further investigation should be done as to the guidance (remarks) included for the date-related attributes in DCEG Sections 27 and 29.

**Comment by JeffWootton** [comment]
Further proposed changes based on research related to this issue:

DCEG clause 27.76:  For the attribute dateDisused, consider that the date at which a feature (such as a dumping ground) is disused would be a single date and not periodic (seasonal).  Therefore it is proposed that the periodic date range formats are removed as allowable formats for this attribute:

![image](https://user-images.githubusercontent.com/70211773/192461439-2cd0f46f-f553-47c9-92e9-2efb67981c30.png)

DCEG clause 27.77:  For the attribute dateEnd, clarify the examples to indicate the inclusive nature of the attribute as explained in clause 2.4.8:

![image](https://user-images.githubusercontent.com/70211773/192465759-acc00e4e-e8c2-4eba-8582-79168a3b6f4d.png)

DCEG clause 27.79:  For the attribute dateStart, clarify the examples to indicate the inclusive nature of the attribute as explained in clause 2.4.8:

![image](https://user-images.githubusercontent.com/70211773/192468000-59a4eaff-bc90-49bd-86bc-85695a3d7b0c.png)

**Comment by Christian-Shom** [comment]
Agree with the proposed amendments.
