### ISSUE TITLE
Offshore Production Area - Water Level Effect

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#44]
It has been noted that offshore wind turbines may be fixed or floating.  Wave and current turbines may be always submerged(?).  Consider adding attribute waterLevelEffect to feature OffshoreProductionArea.

Consider that this may be relevant information at smaller scales where the individual structures within the production area may not be encoded.

**Comment by Christian-Shom** [comment]
How would attribute waterLevelEffect be used by the ECDIS? Isn't attribute category of offshore production area and /or possible overlapping Obstruction area enough?

**Comment by alvarosanuy** [comment]
Currently, **OffshoreProductionArea** features trigger an Indication in ECDIS (irrespective of the attributes encoded).

Portrayal wise, new default symbology has been developed by the PsWG and this can be supplemented by additional symbols based on the result of CS(RESTRN01) which is linked to the values of the attribute Restriction.

If **waterLevelEffect** is to be added to this feature, it wouldn't change the current A&I performance and, we think, it shouldn't impact portrayal. The encoded value should be treated as 'additional info' and become available to mariners by pick report only.

I think there are some views about the potential use of this information when navigating, at large scale, in between the individual structures within the area (sometimes allowed to certain vessels). 

I would like to hear the views of those countries that currently have these types of offshore areas in use and charted.

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  14.6

Points to Note:
-  Note that change has not yet been applied in DCEG.
-  Noting in particular that wind turbines may be fixed or floating, should attribute waterLevelEffect be added to feature OffshoreProductionArea?
-  May be useful for smaller scale ENCs where the individual devices are not encoded, but where the devices are encoded guidance should state that this should be populated on the individual features.

Discussion/Decision:
-  Question was raised as to whether there is any intended impact of this change on symbology of offshore production areas.  It is expected that there would be no impact (information only available by ECDIS Pick Report), although the NCWG Chair reported that there is different symbology for fixed or floating offshore production areas in S-4/INT1.
-  There were some reservations in regard to the merit of applying this change, however it was agreed that this amendment should be made for Edition 1.1.0.

**Action:**
**-  Amend DCEG clause 14.6 to add attribute waterLevelEffect as an allowable attribute for the feature OffshoreProductionArea (IHO Sec).  [Complete]**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**
