### ISSUE TITLE
Traffic Separation Zone/Traffic Separation Line

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#45]
It has been suggested that the features TrafficSeparationZone and TrafficSeparationLine could be merged into a single feature (TrafficSeparationZone).

Can we just have a single feature TrafficSeparationZone (curve and surface) and clarify in the notes that the "zone" is linear where it is a common boundary?

NOTE:  The IHO Hydrographic Dictionary defines the term "Separation Zone (or Line)" as "A zone or line separating the traffic lanes in which ships are proceeding in opposite, or nearly opposite directions; or separating a traffic lane from the adjacent sea area; or separating traffic lanes designated for particular classes of ships proceeding in the same direction.".  

The above term and definition is those from which the TrafficSeparationZone and TrafficSeparationLine features currently included in S-101 have been derived.  All three terms are currently registered in the Concept Register of the IHO GI Registry.  From a Registry Manager perspective, in order to maintain the integrity of the contents of the Registry (and promote consistency) the term "Separation Zone (or Line)" and its definition would need to be adopted in S-101 if the current two features were to be merged into a single feature for encoding a zone or line.

**Comment by KlasOstergren-SMA** [comment]
The term "Separation Zone or Line" (without parentheses) are used in 1972 Collision Regulaitions with the same definition as in the Hydrographic Dictionary.
I cannot really see any advantages with having two separate features for zone and line instead of one feature supporting curve and surface so I will support that suggestion.
