### ISSUE TITLE
Speed Restricted Areas

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#46]
Consider whether speed restriction areas should be modelled as a separate feature in S-101.

Perhaps the addition of a new dedicated feature for speed restricted areas should be considered given that the complex attribute vesselSpeedLimit on RestrictedAreaNavigational only applies to one (perhaps two - noWake?) values of the attribute restriction.

**Comment by rmalyankar** [comment]
If speed-restricted areas also have other restrictions, defining a specific feature type for speed restricted areas would result in multiple spatially coincident objects and pick reports that are more complex from the users' point of view (e.g., they would have to look in one place in the pick report tree for speed restrictions and another place for other restrictions).

**Comment by Christian-Shom** [comment]
- Rejoin Raphael point of view.
- The Complex attribute might be reviewed to encode complex cases. As an example, we have an area where speed is limited to 12 knots for vessels over 20 metres long and 20 knots for the others. Suggest:
**vessel speed limit               C            0,***
   speed limit                      (S)RE      1,1
   vessel minimal length     IN           0,1
   vessel maximal length     IN          0,1
   vessel class                      (S)TE      0,1
Feedback from HOs on other use cases might be useful.

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  17.8, 27.148

Points to Note:
-  Enquiry from a training centre from 2017.
-  Question is how detailed should information be in the navigational ENC?  If there is greater detail required, should this be included in another Product Specification?
-  Note Raphael comment on duplication of areas if there are other restrictions.
-  Suggest that current modelling is OK – no change required.

Discussion/Decision:
-  Given the arguments presented against introducing speed restricted areas as a new feature in S-101, including area duplication and additional requirements being incorporated in other S-100 based Product Specification(s), it was agreed that no action should be taken on this issue.

**Action:**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**
