### ISSUE TITLE
Topmark Colours

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#48]
Consider whether more than one colour should be permitted for Topmarks. IC-ENC has seen instances of topmarks which have two colours. Danish cells include instances. Alternatively shape information could be adapted to be topmark information and these cases incorporated in that complex attribute using text. It may be useful to consult the IEHG on this proposal.  Suggest amend the multiplicity of colour on the complex attribute topmark to 0,*. 

**IHO Sec Comment:** Not sure about this one – if more than one colour is significant and intended to be distinctive to the mariner, would this not be a Daymark?  Requires discussion (for Ed. 1.1?).  Suggest that a remark is included (possible at clauses 18.1 and 29.34) to this effect.

**Comment by LeoKuzmin** [comment]
I am concerned the value {3} (No System) of the "Marks navigational - System of" attribute since there can be used any topmarks and any colours in areas where MARSYS has this value.
As regards structure object which supports a topmark, I'd add feature types Light float and Light vessel. Besides of that a topmark can be installed on on some categories of the Landmark (e.g. cairns) or Daymark. Of course, buoys cannot be equipped by Daymark. 
We consider the difference between Topmark and Daymark by their form and place of the installation on a structure but not by purpose.

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  Sections 18 and 20.

Points to Note:
-  Suggestion is that the capability to define multiple colours for topmarks should be included in the DCEG.
-  Note IHO Sec opinion – consider that where there is navigational significance in multiple colours on topmarks, then these in fact constitute daymarks and should be encoded as such.
-  If colour is to be multiple, does this then mean that we need to add colourPattern?

Discussion/Decision:
-  There was agreement with the suggestion that topmarks having multiple colours that are intended to be used for navigation should be encoded as a Daymark feature and not using the complex attribute topmark.
-  It was agreed that guidance should be included in the DCEG that if a “topmark” that has multiple colours is required to be encoded, this should be done using the Daymark feature.

**Action:**
**-  Amend DCEG as required to include guidance for encoding “topmarks” that are required to be encoded with multiple colours (IHO Sec).  [Complete]  [Post-meeting:  New guidance included at clauses 18.1, 18.3.1.1, 20.13.1 and 29.34.]**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**

**However, please see below contents of email discussion between Netherlands and S-101PT Chair post-S-101PT9:**

Hi Arno:

You are correct currently S-101 only allows one colour value and guidance added in 1.1.0 describes the use of Daymark as a work around (20.13).

I think a proposal to change the multiplicity of colour on the topmark complex attribute would make sense. Colour pattern may also need to be added. Noting that validation checks would probably flag these due to IALA rules and those could be ignored on a case by case basis.

I also note that Landmarks with Topmarks now convert to Daymark features I think this should also be reconsidered as the resulting display seems less clear than in S-52. Nit sure if this is something you’ve come across?

Would the Netherlands like to consider raising this proposal for the PT10 meeting for S-101 1.2.0?

When the S-100WG met in Aalborg I recall a beacon with multiple colours on its topmark so these clearly exist in the real world.

Regards,

Tom

Tom Richardson

Technical and Standards Manager
________________________________________________________________________________________________________________________________

Hi Jeff and Tom,

Just a quick question about topmarks in S-101. Is it correct that a topmark in S-101 only can have one colour?

Or is a topmark with multiple colours considered to be a daymark in S-101?

We do have quite a few buoys with a multi-colour topmark… So we prefer to have the possibility in S-101 to encode topmarks with multiple colours instead of encoding them as daymarks. Is this possible?

![image006](https://user-images.githubusercontent.com/70211773/234011027-73dd6aaa-89ba-4d86-964d-f8dce7a9f5c9.jpg)

**Comment by JeffWootton** [comment]
Refer to Paper [S-101PT10-07.8](https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT10/S-101PT10_2023_07.8_EN_Topmarks_with_Multiple_Colours_V1.pdf), associated Decisions, and Action S-101PT10-23.

Close Issue.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/c0361c1e-da24-415a-8fab-84e29bbbde86)

**Comment by alvarosanuy** [comment]
I do not see the need for any changes to the Portrayal Catalogue. S-52 CSP only uses TOPSHP and not colour.
