### ISSUE TITLE
Category of Runway

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#49]
Given the discrete separate definitions in the IHO Hydrographic Dictionary for "runway" and "heli pad", suggest that consideration is given to removing this attribute and remodelling helicopter landing pad as a separate feature.  This would also resolve the issue of having runway as point primitive.

**Comment by TomRichardson6** [comment]
Support this improved modelling but do not consider it necessary to make this change in edition 1.1.0 of S-101. Propose that it is applied in the next edition.

**Comment by JeffWootton** [comment]
Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Paper S-101PT11-06.1 and related decisions. Changes applied for S-101 Edition 1.2.0 at DCEG clauses 2.3, 2.5.9, 6.4 and 6.5. Edition 1.1.0 attribute categoryOfRunway removed.

Close Issue.
