### ISSUE TITLE
Distributed Remains of a Wreck

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#50]
The distributed remains of a wreck are currently encoded using the attribute categoryOfWreck, value _3_ on a Wrecks feature.

By definition, the distributed remains of a wreck are "A substantively decayed wreck over which it is safe to navigate but which should be avoided for anchoring, taking the ground or ground fishing.".

Is there an argument to remove value for categoryOfWreck of _3_ (distributed remains of wreck) to be a "category of foul ground", given that its relevance in terms of navigation is more related, by definition, to foul ground?

**Comment by mo7Cs** [comment]
Agree - foul ground is more appropriate.

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  13.5, 13.7, 27.69

Points to Note:
-  By definition, the distributed remains of a wreck are considered safe to navigate over, which may be considered to be more suited to the feature FoulGround.
-  Thinking further on this, the same situation exists in regard to obstructions in general (Obstruction) and wrecks and underwater rocks which are their own features but also considered to be obstructions.  Suggest therefore that the current modelling is OK and any changes will likely complicate things further.

Discussion/Decision:
-  While it was conceded by the Sub-Group that there is merit in considering the distributed remains of a wreck as foul ground, it was agreed that there is nothing wrong with the current modelling as a category of wreck (noting that there is no implication in the definition of a wreck that it is always to be considered to be an obstruction to navigation).
-  It was agreed that there may be some overlap between this issue and discussions related to Issue #30 (possibility of a “category of foul ground” attribute).
-  It was agreed that the current modelling is to be retained for Edition 1.1.0, however this issue may need further discussion pending the outcome of discussions regarding Issue # 30.

**Action:**
**-  Issue to remain open for further discussion, possibly in relation to Issue #30.  [Ongoing]**

**Comment by JeffWootton** [comment]
Issue #30 closed - no new attribute categoryofFoulGround at this time, therefore retain current modelling.

Note that, while S-4 states that the distributed remains of a wreck should be charted using the foul ground symbol, there is no direct specification in S-4 that the distributed remains of a wreck constitute a "type" of foul ground.

Close Issue.
