### ISSUE TITLE
Optimum Display Scale

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#53]
In their review of the PS main document, NIWC asks for the (re?)introduction of an Optimum Display Scales.
![image](https://user-images.githubusercontent.com/71139640/196128678-ec342d9c-76d6-4f67-b1bf-9320e3ed4cbd.png)

My view is that Max and Min Display scales are sufficient in terms of Dataset loading and display, and that we should go forward with the Spec 1.1.0 as it is now. If testing reveals that something is missing, then we may reconsider NIWC proposal.

**Comment by Christian-Shom** [comment]
Comment from AUS in the PS review:

- Is the use of **optimumDisplayScale** necessary? We thought it was discontinued. Is it expected to be used somehow by ECDIS???
- Review the need for **optimumDisplayScale**.

**Comment by Christian-Shom** [comment]
There was a consensus in the Sub-Group meeting 2022-10-19 that Optimum Display Scale is not necessary for dataset loading/Unloading and data drawing and thus should be removed from the draft document for edition 1.1.0. If future tests show that there is a lack, this could be re-considered for next edition.

The following was agreed :
o	Check with the S-101 PT Chair the reason for the re-introduction of optimum Display Scales in the S-101 PS main document, clause 12.1.2.2.
![image](https://user-images.githubusercontent.com/71139640/197195604-9e6a4b36-7ef6-4920-87cd-f488e9ed49f0.png)


Post-meeting : Tom Richardson confirmed that optimumDisplayScale is not mandatory in S-100 5.0.0 (multiplicity 0…1). He agreed that this should be aligned in S-101 §12.1.2.2 and that references to Otimum Display Scale could be removed (this will be applied by Jeff) in the draft document for 1.1.0. Yet, this issue will be presented at PT9.

**Comment by JeffWootton** [comment]
S-101PT9 decision was to not include optimumDisplayScale at this time.  Close Issue.
