### ISSUE TITLE
Scales guidance in the DCEG

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#54]
In the current DCEG, we find some guidance on Scales. At this stage, and to make this revision simple, I suggest:
1. Aligning the definitions (Max and Min Display Scales) on what has been decided for the Main document (just definitions, without extended details);
2. Removing redundancies with the Main document:
- Remove figure 2.2 and the text underneath;
- Remove figure 2.3.
The idea is that the main document should provide guidance on how setting the scales and building an ENC scheme, whereas the DCEG is for guidance on how encoding data in a dataset.

**Comment by JeffWootton** [comment]
The following actions have been taken for consideration for S-101 Edition 1.2.0:
- Terms and definitions have been consolidated in the S-101 Main document and the terms and definitions in the DCEG (clause 1.3.1) have been replaced with a reference to the S-101 Main document (clause 1.3.2).
- Figures and paragraph have been removed from DCEG clause 2.5.5.
- A reference to S-101 Main document Section 4.5 (Datasets) has been added at DCEG clause 5.5.

**Comment by alvarosanuy** [comment]
Make sense to me.

**Comment by JeffWootton** [comment]
DCEG changes as summarised above approved at S-101PT10.  Close Issue.
