### ISSUE TITLE
Channel Dimensions for Fairways

### ISSUE THREAD

**Issue by Megan-NOAA** [iho-ohi/S-101-Documentation-and-FC#57]
Currently there is no way to add the channel dimensions (width and length) to a FAIRWY object in S-57 and this information is represented on our RNCs through a table for channel depths.  Can attributes please be added in S-101 to account for project width and project length so that the user does not have to measure channels and can instead receive the information through the pick report of the feature? We at NOAA have received numerous requests from the public and other stakeholders to have this information added as more are using ENCs in place of the RNCs for navigation.

**Comment by JeffWootton** [comment]
We have the already registered attributes horizontalLength and horizontalWidth, that may be used for this purpose.

I would be interested in any feedback from mariners as to how this information would actually be used when voyage planning or monitoring?  Would this information be better included in a Nautical Publication?

My other concern is consistency.  If we apply this for fairways, will we also be obliged to apply this for other routeing measures (traffic separation lanes, deep-water routes, two-way routes)?

**Comment by alvarosanuy** [comment]
> I would be interested in any feedback from mariners as to how this information would actually be used when voyage planning or monitoring?

Me too :)

**Comment by JeffWootton** [comment]
Refer to discussions at DCEG Sub-Group 4 meeting (September 2023).  No further action required.

Close Issue.
