### ISSUE TITLE
Encoding Lights with a specific pattern

### ISSUE THREAD

**Issue by RichardCoyles** [iho-ohi/S-101-Documentation-and-FC#58]
Currently S-101 DCEG (1.1) gives no guidance as to the encoding of lights with an unusual shape/pattern, for example 3 lights disposed in the shape of a triangle (INT1 - P15)

I suggest guidance similar to that below to be included in the DCEG. 19.1.7 (Various Special Types Of Lights),
after vertically disposed lights:

TYPE - Specific Pattern / S4 - B471.8 /  categoryoflight - undefined / REMARKS - _Where lights are arranged in a specific pattern this should be indicated using either text or an image on the complex attribute information_
e.g 'lights disposed in the shape of a triangle' (MLTYLT = 3)

comments welcome.

**Comment by JeffWootton** [comment]
Have added the following to Table 19-2 for consideration of the DCEG Sub-Group:

![image](https://user-images.githubusercontent.com/70211773/234859750-d2a3ec65-7a9d-40c3-a9ea-9b2271d115cf.png)

Note that there is no mention in this revision of including an image.  The attribute pictorialRepresentation is not a biding attribute for lights features.

**Comment by DavidGrant-NIWC** [comment]
>Note that there is no mention in this revision of including an image. The attribute pictorialRepresentation is not a biding attribute for lights features.

Unless it was changed, I believe `pictorialRepresentation` can be bound to lights through `AdditionalInformation` -> `NauticalInformation`

**Comment by JeffWootton** [comment]
Change approved at S-101PT10.  Close Issue, noting comment from @DavidGrant-NIWC that an image can be included of the pattern via an associated instance of NauticalInformation.
