### ISSUE TITLE
Default value of Vertical Datum for heights

### ISSUE THREAD

**Issue by LeoKuzmin** [iho-ohi/S-101-Documentation-and-FC#59]
Unfortunately, I didn't find any point regarding the discussion of the encoding of default Vertical Datum for heights. Probably, the theme has been discussed early and the final solution has been approved. However, according to the latest documents on this site, the issue looks strange and unclear. Therefore, I decided to raise this issue.

According to the latest edition of S-101 Prod. Spec we have no place to encode default value of datum for heights. It was even removed from S100_DatasetDiscoveryMetadata of the .xml file. Does it mean that we mustn't encode default value of datum for heights at all? Although, the clause 3.9.1 of DCEG points that a "default value for the vertical datum is stored in the Dataset Discovery Metadata in the Exchange Set Catalogue"
If you intend only to encode this information by means of the meta feature objects Vertical Datum of Data (M_VDAT) or by populating the attribute vertical datum on individual geo features in according with DCEG 3.9, it should be specified in the S-101 Prod. Spec.

On the other hand, why cannot S-101 dataset encode the default Vertical CRS for heights? Although S-100 does not prohibit the using of a CRS record to encode a vertical datum for heights and there are all needed things to encode it in the CRS record. It looks strange that we have always encoded the VDAT sub-field in S-57 datasets but now it is not used for vertical datum for heights in S-101 datasets.
My point of view, it will be logical to have description of all CRSs in one place in the dataset header. In this case we don't always need to create an additional meta feature Vertical Datum of Data covering the land areas or the entire of dataset. We keep a usual and clear way to encoding vertical datums as for soundings as for heights.

**Comment by DavidGrant-NIWC** [comment]
https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT9/S-101PT9_2022_INF1-01_EN_Metadata_Issues_V1.pdf

![image](https://user-images.githubusercontent.com/62906211/214619600-ee24f4b7-23ea-41de-a616-22a900f48848.png)

**Comment by LeoKuzmin** [comment]
Thank you very much David.
There is the "Recommended Changes" page in the referenced presentation.
Could you confirm that decision has been approved and will be included to the coming version 1.1.0 of S-101 Prod. Spec.?
Does it mean that we have to encode all "default" metadata values by means of meta feature objects covering the whole dataset? Of course, they don't have to overlap meta features of the same type with other attribute values if they are.
As regards CRSH/VDAT, AXTY=12 (Sounding datum), if it is removed, how would we use the field C3IL/VCID in the Soundings' coordinates tuples?
In any case, in my strong opinion we have to keep information about "default" Sounding and Vertical datum at least in S100_DatasetDiscoveryMetadata of the CATALOG.xml file.

**Comment by DavidGrant-NIWC** [comment]
> Could you confirm that decision has been approved and will be included to the coming version 1.1.0 of S-101 Prod. Spec.?

This will not be addressed in v1.1.0. I have been unable to get this issue addressed during a meeting. The referenced presentation from S-101PT9 was strictly an "INFO" presentation and was not presented or discussed during the session.

> In any case, in my strong opinion we have to keep information about "default" Sounding and Vertical datum at least in S100_DatasetDiscoveryMetadata of the CATALOG.xml file.

Datum information is not available in the discovery metadata. See S-100 Part 17.

> Does it mean that we have to encode all "default" metadata values by means of meta feature objects covering the whole dataset?

No (for v1.1.0). However, if a default value is not provided via such a feature (e.g., SoundingDatum) then the default datum will not be available for processing within the portrayal rules and will not be shown in the pick report (unless the OEM adds custom processing for S-101). It should however be available in the legend.

Note in the screenshot below that there is no SoundingDatum feature shown in the pick report (because there aren't any of these features in the dataset), but the sounding datum is shown in the legend:
![image](https://user-images.githubusercontent.com/62906211/216092179-39cfa84c-c21b-4cab-90a3-d749a7ee1ac5.png)

**Comment by JeffWootton** [comment]
Note that this issue also impacts on statements made at DCEG clauses 3.8.1 (Sounding Datum) and 3.9.1 (Vertical Datum); and the S-101 Main document.  Please refer to the following email trail (read from bottom up:

[verticalAndSoundingDatum Email Trail.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/11343744/verticalAndSoundingDatum.Email.Trail.docx)

@DavidGrant-NIWC :  Will you please consider submitting your S-101PT9 INF Paper to S-101PT10 as a full submission for discussion and possible follow-on action to the S-100WG?  As the INF paper was not discussed at S-101PT9 and with the discussion above I think this is warranted,

**Comment by DavidGrant-NIWC** [comment]
> consider submitting your S-101PT9 INF Paper to S-101PT10

Mikan and I will try to get an updated submission put together.

**Comment by JeffWootton** [comment]
Refer to Paper [S-101PT10-09](https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT10/S-101PT10_2023_07.9_EN_Vertical_Datum_Information_in_S-101_V1.pdf).  To be discussed by DCEG Sub-Group.

**Comment by JeffWootton** [comment]
Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Papers S-101PT11-06.1 and S-101PT11-08. 10, related decisions and Actions S-101PT11-40 to 42. Changes applied for S-101 Edition 1.2.0 at DCEG clauses 3, 3.3, 3.9 and 3.10.

Close Issue.
