### ISSUE TITLE
DCEG (Ed 1.0.1) clause 2.4.10 - Colours and Colour Patterns

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#6]
Original DCEG Review comment:  This (population of colour for border stripes) is messy, and note that colour pattern only has multiplicity [0,1] where it is used throughout the DCEG.  Needs to be discussed.
SHOM:  A general comment on colours and pattern: how is all this used by the mariner? I imagine he has to read the Pick Report. For all "complex cases" not sure it really helps. There is no specific portrayal (which I fully understand). Shouldn't we give advice to the encoder, in the DCEG, to provide external files (images) when possible?
IHO Sec:  Agree with SHOM comments.  The DCEG describes for encoders how to encode these combinations, but is this the understanding (knowledge) of the mariner in regard to interpretation?

Would appreciate any opinions (from both encoders and end users) regarding the encoding of colour/colour pattern combinations.

**Comment by alvarosanuy** [comment]
I think the DCEG should strongly recommend producers to include an image when encoding a non-IALA mark that uses multiple colours and patterns.
There's no way mariners can easily make sense of the proposed numbering sequences, particularly in high stress situations .....

Related to this topic, I noticed that the feature attribute **categoryOfSpecialPurposeMark** is not mandatory for the feature **Daymark**. When colours and patterns do not follow IALA conventions, I think it's paramount to provide mariners a clear description of the purpose of the mark. The _'what for'?_ question .......
Consequently I propose  we consider making the feature attribute **categoryOfSpecialPurposeMark** mandatory (1,*) for **Daymark**.
This is currently the case for other 'ambiguous marks' such as **BeaconSpecialPurposeGeneral** & **BuoySpecialPurposeGeneral**.

**Comment by JeffWootton** [comment]
Have included new guidance for recommended inclusion of an image using attribute pictorialRepresentation at clause 2.4.10 and additionally at clause 20.14.1 (for daymarks). Regarding categoryofSpecialPurposeMark on feature Daymark, do not think that this should be mandatory as the daymark may be performing the function of a IALA aid (lateral, cardinal, safe water, ..) in which case categoryofSpecialPurposeMark is not required.

Close Issue pending any further discussion.
