### ISSUE TITLE
CurrentNonGravitational mismatch between 1.1 DCEG and 1.1 FC for allowed primitives

### ISSUE THREAD

**Issue by TDYCARHugh** [iho-ohi/S-101-Documentation-and-FC#62]
The 1.1 FC CurrentNonGravitational has point, curve and surface as allowed primitives but the DCEG and Portrayal catalogue only identify this feature as a point.

**Comment by alvarosanuy** [comment]
My understanding was that Curve and Surface were already removed in FC 1.0.2 (refer to last entry comment in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/36). Maybe we just looked at the change made in DECG 1.0.2 and assumed the change was made to the FC (as it should). The PsWG agreed on removing these 2 geometric primitives as stated by the DCEG. Recommend fixing FC 1.1.0 to match DCEG.

**Comment by JeffWootton** [comment]
Agree with Alvaro.  S-101PT decision was that if it was required to create an area surface current, this should be done by creating a S-100 product.
