### ISSUE TITLE
Buried Depth for Tunnels

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#65]
Please refer to the following discussion between myself and Hugh:

**T-Caris:**  Hi Jeff,
Do you think it is worth mentioning in S-65 that the attribute BURDEP will be dropped when migrating to Tunnel in S-101. 
I am mentioning it because in S-52 there was a different portrayal of Tunnel when BURDEP=0 .
If someone does a round trip conversion from S-57 to S-101 (dropping BURDEP) and then produces S-57 from the S-101 data then BURDEP won’t be populated and the Tunnel may display differently.

**IHO Sec:**  Hi Hugh.
Thanks for picking this up.  We dropped buriedDepth from the Tunnel feature because at the time it was thought that there was no use case provided at the time to retain it.  As far as I am concerned you have provided us with a use case in regard to ECDIS portrayal to reinstate buriedDepth as an allowable attribute for Tunnel.  There is certainly no intent in regard to the S-101 data model to modify the model such that it removes a portrayal requirement.  I will include this as a discussion item for our next DCEG Sub-Group meeting.
You have raised a point that was not really considered when the S-101 data model was being developed, this being that if there was S-57 attribution required to satisfy a portrayal requirement in S-52 this may have been overlooked when we were considering amendments to the data model in S-101.  If you come across any other such instances in S-101 please let me know.
 
**T-Caris:**  Hi Jeff,
In S-52 the TUNNEL portrayal was this
"TUNNEL","","LS(DASH,1,CHGRD)","4","O","OTHER","32250"
"TUNNEL","BURDEP0­","LS(DASH,2,CHBLK)","4","O","STANDARD","24010"
Default is 1 pixel wide grey dash line but if Tunnel is not buried than it is  2 pixels wide black.
My recollection is Mike Eaton saying something like “who cares if there is a tunnel unless it is not buried and I don’t want to drop an anchor on it”.
My real point is that if a Tunnel gets round tripped to S-101 and back it will lose the BURDEP and change how it is portrayed.  From the portrayal point of view I think that a Boolean whether the tunnel is buried under the navigational portion of it or not would suffice.  The actual depth may not be of much use.

**IHO Sec:**  Hi Hugh.
Thanks for this.  I have tentatively added a new Boolean type attribute isBuried for the Tunnel feature and will add a GitHub issue for this to be discussed.  My only concern with this is that buriedDepth is already included in S-101 for the CableSubmarine and PipelineSubmarineOnLand features so there is now a minor inconsistency in the modelling.  I suppose the question to be asked is why is the portrayal of an encoded tunnel different in S-52 based on the value populated in BURDEP but the same does not apply for CBLSUB and PIPSOL?  My best guess is that cables and pipelines are considered to be just as important whether they are buried or sitting on the seabed so there was no thought in varying the portrayal; or a tunnel (normally vehicular) constructed under a body of water would normally be buried deep enough so as to ensure no risk of damage from marine activities while this may not be the case for a cable or pipeline.  Anyway, will see where the discussion takes us ...
The other thing that I find interesting is that there is no guidance in the UOC for population of BURDEP = _0_ for tunnels that are not buried in order to drive specific portrayal in S-57/S-52 ECDIS (given that the lookup table is specific to a value of _0_) ...

Please note the possible inconsistency that would exist between the modelling of isBuried for the Tunnel feature as compared with buriedDepth for CableSubmarine and PipelineSubmarineOnLand.  I am interested to have anyone's opinion on this.  @alvarosanuy - please note possible implications on portrayal.

**Comment by alvarosanuy** [comment]
Hi all,
I did a bit of research, and it looks BURDEP was dropped as an allowable attribute for TUNNEL at some point before S-57 Ed 3.1.3 (the attribute is struck-through in section 4.8.3 of AUOC 4.3.0).
This means that we shouldn't be concerned about BURDEP for Tunnel as there shouldn't be any non 3.1.3 ENCs out there ... 
The migration to S-101 should report the existence on an unconforming attribute and stop the conversion until the issue is fixed in the S-57 dataset.

**Comment by JeffWootton** [comment]
Agree with Alvaro that BURDEP is not an allowable attribute for TUNNEL in S-57 (refer UOC clause 4.8.3). Therefore, the portrayal as listed in the TUNNEL entry in the S-52 Look-Up tables is redundant, as the corresponding S-57 encoding is not possible. I have therefore reverted the DCEG by removing the newly proposed Boolean attribute isBuried.

Close Issue.
