### ISSUE TITLE
New or remodeled categoryOfAnchorage attribute value

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S-101-Documentation-and-FC#66]
For context refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/116

This issue is to discus the merits of either, creating a new **categoryOfAnchorage** value 11 (dangerous or hazardous cargo) or renaming **categoryOfAnchorage** value 4 (explosives anchorage) to the more generic term 'dangerous or hazardous cargo'.

**Comment by JeffWootton** [comment]
Perhaps another option could be adding the categoryofCargo attribute to AnchorageArea and AnchorBerth and removing categoryOfAnchorage = _4_ as an allowable value for these features in S-101? From a modelling perspective, this may then better align these features with the Berth feature.

Requires discussion by the S-101 DCEG Sub-Group

**Comment by JeffWootton** [comment]
**Discussion at S-101 DCEG Sub-Group 4 meeting:**

**Points to Note:**
-  The proposal is to amend the attribute categoryOfAncorage = 4 (explosives anchorage) to “dangerous or hazardous cargo”; or add a new “dangerous or hazardous cargo” value to categoryOfAncorage. The proposal is intended to ensure consistency of the features AnchorageArea and AnchorBerth with the revised modelling that has been approved for the Berth feature.

**Discussion/Decision:**
-  It was suggested that the more consistent alternative would be for the categoryOfCargo attribute to be added to the AnchorageArea and AnchorBerth features; and categoryOfAncorage = 4 (explosives anchorage) to be removed as an allowable value for these features. This was approved by the Sub-Group.

**Action:**
**-  Include draft amendments to the DCEG in line with the discussions/conclusions of the Sub-Group, for approval at S-101PT11 (IHO Sec). [Complete]**

Approved at S-101PT11 with no further discussion. Close Issue.
