### ISSUE TITLE
marks navigational – system of & Preferred Channel marks

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S-101-Documentation-and-FC#67]
Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/79 PsWG decision comment made on 22/5/23.
Note that a new range of coloured navmarks symbols have been introduced in S-101 and that the mapping of the correct 'preferred channel mark' symbol would significantly benefit from some modelling changes and additional encoding guidance.

**The PsWG asks the DCEGsWG to :**

1. Include the attribute "marks navigational – system of" in **VirtualAISAidToNavigation** in order to assist with the mapping of the correct 'preferred channel mark' symbol. Although this task can be resolved by LUA scripts, the preferred option is to avoid performing topological tasks during the portrayal building.

2. Making the encoding of the attribute "marks navigational – system of" mandatory when 'category of lateral mark' = 3 or 4 **OR** 'virtual AIS aid to navigation type' = 7 or 8.

**Comment by JeffWootton** [comment]
for (1): Note that in S-101 Edition 1.1.0 there was an error for attribute virtualAISAidToNavigationType values _5_-_8_, which has now been corrected in the draft S-101 DCEG Edition 1.2.0 to correctly align with the corresponding encoding for the S-57 Object class NEWOBJ:
![virtualAISAidToNavigationType](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/4b832128-b412-489a-a899-422f3cc0884e)

This correction was approved at the S-101PT10 meeting (June 2023). Given that this correction now includes the relevant IALA buoyage system as part of the attribute values and there are no longer values for "preferred channel" marks (which also aligns with IMO), there is no longer a requirement to add the attribute marksNavigationalSystemOf to the VirtualAISAidToNavigation feature. Therefore suggest that no further action is required.

For (2): The overall indication of the buoyage system for a dataset is indicated by the value of marksNavigationalSystemOf on the mandatory Meta feature NavigationalSystemOfMarks; and it is prohibited to populate marksNavigationalSystemOf on individual Geo features if the value is the same as for the underlying NavigationalSystemOfMarks feature. Therefore, if a preferred channel lateral mark is aligned to the overall system, then it is prohibited to populate marksNavigationalSystemOf on the feature itself. Therefore mandating marksNavigationalSystemOf as suggested will not work in most cases.

The only way that I can see the correct symbol being displayed if the portrayal is to be entirely based on the value populated for categoryOfLateralMark is if the selected symbol is also somehow associated to the value populated for marksNavigationalSystemOf on the underlying NavigationalSystemOfMarks feature. [By the way - this will be the case for **all** values of categoryOfLateralMark.] This needs to be noted https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/79.

To be discussed by DCEG Sub-Group.

**Comment by alvarosanuy** [comment]
@JeffWootton  - Sorry I was not present when this topic was discussed at S101PT10 and I may be missing or misinterpreting something here but, based on the new list of values for **virtualAISAidToNavigationType**, are we now saying that IALA/IMO do not support the 'preferred channel' concept for V-AIS?

**If this is the case, this issue can be closed as we won't be using the V-AIS preferred channel symbols that we had developed (see below).**
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70189016/7b9ba9e7-1a2a-4d66-aa7c-a082318d35eb)


The concept certainly exists for physical buoys and beacons and they have their unique symbology depending on the IALA system in force.
For physical navaids the right symbology can be implemented by linking **categoryOfLateralMark** and **marksNavigationalSystemOf** (see DCEG table below).

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70189016/35389fab-1695-4af2-9609-f023ed81603c)

**Comment by JeffWootton** [comment]
**Discussion at S-101 DCEG Sub-Group 4 meeting:**

**Points to Note:**
-  This Issue resulted from observations made for the attribute virtualAISAidToNavigationType, which contained errors in the attribute values which were corrected at S-101PT10.

**Discussion/Decision:**
-  After summary of the amendments that had been made for attribute virtualAISAidToNavigationType to make consistent with IMO requirements and the values implemented for the NEWOBJ object in S-57, it was agreed that the requirement mentioned in the Issue no longer existed.
-  It was noted that it is prohibited to encode marksNavigationalSystemOf on an aid to navigation feature that defines the same buoyage system as that defined by the underlying NavigationalSystemOfMarks feature.
-  It was observed that, if types such as preferred channel lateral marks are going to be incorporated into virtualAISAidToNavigationType in future and the preference is not to indicate the buoyage system in the attribute value, an implicit relationship would need to be established between the geo feature and the underlying NavigationalSystemOfMarks feature.

**Action:**
**-  Report to S-101PT11 and close Issue (IHO Sec).**

No further discussion at S-101PT11. Close Issue.

**Comment by JeffWootton** [comment]
**Discussion at S-101 DCEG Sub-Group 4 meeting:**

**Points to Note:**
-  Suggestion is that if the characteristics of a buoy installed as an emergency wreck marking buoy are not aligned with the IALA defined characteristics then the mark is actually a wreck buoy and should be encoded as such. Therefore allowable attribute encoding combinations that do not align with IALA should be removed for BuoyEmergencyWreckMarking.

**Discussion/Decision:**
-  The meeting agreed that encoders should be able to encode a BuoyEmergencyWreckMarking no matter what the characteristic of the buoy are if it is communicated that this is the intention of the buoy.
-  It was, however, agreed to remove superbuoy and ice buoy as allowable buoy shapes for BuoyEmergencyWreckMarking.

**Action:**
**-  Include draft amendments to the DCEG in line with the discussions/conclusions of the Sub-Group, for approval at S-101PT11 (IHO Sec). [Complete]**

Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Paper S-101PT11-06.1 and related decisions. Changes approved for S-101 Edition 1.2.0.

Close Issue.
