### ISSUE TITLE
Emergency Wreck Marking Buoy - Review list of attribute values

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S-101-Documentation-and-FC#68]
My opinion is that, for EWM buoys, the number of attribute values available for **colour**, **buoy shape** & **colour pattern** should be much shorter as this feature (EWM) is very specific. If the feature does not comply with the colours and pattern for an EWM then, I believe, it should be encoded as a  **Buoy Special Purpose/General** with **category of special purpose mark** = 60 (wreck mark) instead (not sure about the real life difference though ...).
We may be flexible with the **buoy shape** (although I would recommend discontinuing, at least, values 7 (superbuoy) and 8 (ice buoy). Shapes <> than Spar and Pillar should be encoded with **marks navigational – system of** = 9 (no system).

Also, regarding the attribute **topmark**, is it worth restricting **topmark/daymark shape** to just 8 (upright cross)?
**colour** could be also restricted to 6 (yellow) but it does not affect portrayal so ..... less critical.

**Comment by JeffWootton** [comment]
Agree with removal of values _7_ (superbuoy) and _8_ (ice buoy) as allowable vales for buoyShape.

The general convention for all buoys/beacons in both S-57 and S-101 is that attribution is not restricted (in general) to essentially only the values that conform to IALA conventions. I therefore recommend that, other than the  removal of values _7_ (superbuoy) and _8_ (ice buoy), no further changes are made for BuoyEmergencyWreckMarking.

**Comment by mikan66** [comment]
We should establish a procedure for handling "stale" attribute values that may exist within portrayal rules.  This could involve top-level guidance from the IHO, i.e. look at DCEG and not within rules for official valid values.  Furthermore, feeding these "removals" back into the portrayal catalog could also be done.  Note, however, that modifying tested portrayal rules will require retesting of the rules.  Generally, removal of attribute processing from existing rules has not been happening.

**Comment by JeffWootton** [comment]
**Discussion at S-101 DCEG Sub-Group 4 meeting:**

**Points to Note:**
-  Suggestion is that if the characteristics of a buoy installed as an emergency wreck marking buoy are not aligned with the IALA defined characteristics then the mark is actually a wreck buoy and should be encoded as such. Therefore allowable attribute encoding combinations that do not align with IALA should be removed for BuoyEmergencyWreckMarking.

**Discussion/Decision:**
-  The meeting agreed that encoders should be able to encode a BuoyEmergencyWreckMarking no matter what the characteristic of the buoy are if it is communicated that this is the intention of the buoy.
-  It was, however, agreed to remove superbuoy and ice buoy as allowable buoy shapes for BuoyEmergencyWreckMarking.

**Action:**
**-  Include draft amendments to the DCEG in line with the discussions/conclusions of the Sub-Group, for approval at S-101PT11 (IHO Sec). [Complete]**

Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Paper S-101PT11-06.1 and related decisions. Changes approved for S-101 Edition 1.2.0.

Close Issue.
