### ISSUE TITLE
Update PS reference to performance standard

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#70]
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/0658baaf-ffe0-431f-bce4-04d220cf9316)

MSC.232(82) -> MSC.530(106)

**Comment by JeffWootton** [comment]
Amendment made at main document, clause 4.7, for draft S-101 Edition 1.2.0. Close Issue.
