### ISSUE TITLE
Data Display Algorithm

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#71]
See S-101 PS 1.1.0, noting also discussion from #55:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/62fd90c7-a0d7-4e51-94a8-718495d634b0)

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/a1f26be7-b31a-402f-a3de-c10859815199)

**Comment by DavidGrant-NIWC** [comment]
### Summary
The inability to display the data properly is yet another problem caused by trying to assign multiple purposes to a single attribute value. It seems like a lot of effort to avoid using something we already know works (navigational purpose). Call it something else if the term is offensive - _portrayalSynchronizationValue_ for instance; the attribute could be added to the DataCoverage feature as a Portrayal Attribute:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/b6eeffc0-9bd8-4189-811c-8198f4b825cc)

### Results of prototyping
Here's what I found when investigating using _minimumDisplayScale_ for selecting "side-by-side" rendering:
* It forces producers to select a single minimum display scale for each intended usage, or at least to agree on a range of values which are intended to provide seamless coverage.
  * Here's an example of two existing harbour charts with different compilation scales (1:20k and 1:5k). These draw correctly in S-52 because they have the same navigational purpose.
  ![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/7bfdc5ba-bb09-4b6e-865a-70efa3b5a208)
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/f450644f-28e4-4526-b85b-d168d0086817)
  * There are other examples with band 5 charts at 1:40k.
  * NOAA does plan to re-scheme, but their plan includes two compilation scales in each usage band:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/0fa00e05-9cf8-4b6c-85a6-d20513380af9)

* Data converted from S-57 would need to examine the navigational purpose and assign a preset _minimumDisplayScale_ for each purpose, or it won't render correctly in S-101. In the example above, I assume both datasets would have a _minimumDisplayScale_ of 1:40k. The 1:5k chart is not particularly useful at 1:40k.
* Geographically adjacent data producers with different cataloging schemes will have issues at national boundaries since their standard values for _minimumDisplayScale_ may not agree with one another.

**Comment by alvarosanuy** [comment]
What Dave highlighted applies to the vast majority of ENC portfolios around the world.

I believe that the data loading algorithm shouldn't use **minimumDisplayScale** or **maximumDisplayScale**. There's currently no logical consistency within national portfolios (and less internationally). For this to effectively work in practice it will require a lot of rethinking and rework at the national and international level. I am of the opinion that data producers already have enough on their plates to get their DF ENC production sorted from 2025.

It seems more logical to reinstate the Navigational Purpose concept (that is currently used in the dataset metadata by the way).
Producers are currently mandated to 'label' the **navigationPurpose** of their products in the S100_DatasetDiscoveryMetadata (Port, Transit or Overview).
In my opinion, we just need this info to be exposed to portrayal so it can be used to assist with the rendering of data in ECDIS.

**Comment by DavidGrant-NIWC** [comment]
> It seems more logical to reinstate the Navigational Purpose concept (that is currently used in the dataset metadata by the way).

* As you note, there are only three possible values of S100_NavigationPurpose.
  * We will need a value for each of the generalizations that producers are currently maintaining.
    * This means we probably need six values, especially during dual fuel if we plan on having S-101 and S-57 charts on the screen at the same time.
  * Adding more values to S100_NavigationaPurpose would require a change to S-100, so it can't happen in time to address this issue.
* The group has been very strongly opposed to using navigational purpose for anything other than cataloging but have presented no viable alternatives.
  * Hence my suggestion to present this as a portrayal attribute. However, I'm on board with any solution that resolves this issue.

**Comment by alvarosanuy** [comment]
Below is an extract from @HolgerBothien draft proposal uploaded to the 'Loading Algorithm' issue https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/55#issuecomment-1721306888. For ease of reading and focus on the discussion point I deleted all other S101 PS content.

This is the only proposal at this point in time. Please consider the comments made above when assessing the practical implementation of Holger's proposal.

[Data Display Algorithm - Holger's proposal.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/12877372/Data.Display.Algorithm.-.Holger.s.proposal.docx)

**Comment by DavidGrant-NIWC** [comment]
Note issue at boundary of two band 5 datasets:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/0e8d8610-d065-4f89-bb46-37a50307a2c2)

These two beacons are obscured because the datasets are stacked rather than interleaved (I zoomed in to 1:1k to get the beacons to be placed entirely on the bottom chart):
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/d4859050-127d-44f0-9469-966d742113e6)

Bottom dataset display scale is 22k-45k, top dataset is 12k-22k. Both datasets originate from S-57 band 5 and would be interleaved when drawn per S-52.

This issue occurs with both Holger's proposed algorithm and the algorithm we are currently using in the test bed.

**Comment by alvarosanuy** [comment]
> his issue occurs with both Holger's proposed algorithm and the algorithm we are currently using in the test bed. Similar issues can occur with soundings, text, symbols, sector arcs, leg lines, and leading lines.

Can we have the views from other ECDIS Test beds? I'm thinking of KHOA's and Geomod's (?). Not sure if any other OEM has prototyped S101.
We really need to get this issue sorted. 
At this point in time the only implementer identifying issues with the 'Data Display' principles (algorithm) has been NIWC. 
They suggest the reintroduction of the 'Navigational Purpose' concept (name can be discussed if it hurts some feelings ..) as away to fix the reported problems.
To complicate things even further, we haven't seen any Dual Fuel ECDIS prototype behavior so far! How is interleaving going to work between S-57 and S-101? What's the common language to use?

**Can we please have KHOA/Geomod (or any other) views and experiences implementing 'Data Display'?**

**Comment by benhazelgrove** [comment]
Using KHOA Viewer we have an example of the portrayal.

The DataCoverage features values are shown below.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/141597835/d37153e8-5071-4450-9d65-d05b40cc11e4)

The first image is drawn at 1:69675

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/141597835/e49bfc9f-f0f1-478c-a3f2-a9fa904f16d6)


In the next image I have zoomed to 1:48772 to force the display of the features.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/141597835/7edbc885-6cd0-461e-918a-7b2a60cc69a5)

As we can see it is behaving in the same manner as the NIWC dataset.

**Comment by benhazelgrove** [comment]
This is now relying on the testing of drawingIndex?

**Comment by JeffWootton** [comment]
S-101 Decision related to discussions on paper S-101PT13-07.4: S-101 Annex D to be removed from S-101 and included as a new Annex to S-98.

New S-98 GitHub Issue [#58](https://github.com/iho-ohi/98-interoperability/issues/58) opened 23/07/24.

Close this Issue.
