### ISSUE TITLE
101FR00369660.000 no default vertical datum - DCEG issue?

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#73]
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/45dfb1ba-0376-46a6-965d-f1960e348422)

The dataset has a default sounding datum, but no default vertical datum. There is a VerticalDatumOfData feature (highlighted above), but it doesn't cover the entire dataset. This means there is no vertical datum available in the legend for parts of the chart.

The DCEG doesn't say whether this is allowed (VerticalDatumOfData feature with no default vertical datum). Should this be clarified? Might OBE depending on what happens with #72

**Comment by JeffWootton** [comment]
Agree that this needs to be taken up in the wider discussion on defining sounding and height datums in ENC.

**Comment by JeffWootton** [comment]
Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Papers S-101PT11-06.1 and S-101PT11-08.10, related decisions and Actions S-101PT11-40 to 42. Changes applied for S-101 Edition 1.2.0 at DCEG clauses 3, 3.3, 3.9 and 3.10.

Close Issue.
