### ISSUE TITLE
DCEG 3.9 Vertical datum references non-existent Discovery Metadata field

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#74]
3.9.1 para 2 refers to a dataset discovery metadata field which doesn't exist:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/2fc557f8-64df-4530-b8de-807e779097b4)
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/db47885d-e954-4ded-9837-9666fcf4bdb9)

Currently, the default vertical datum is (optionally?) stored in the dataset encoding in the CSID (Coordinate Reference System Record Identifier). Maybe OBE by #72?

See also #73

**Comment by JeffWootton** [comment]
This has been flagged for discussion within the DCEG Sub-Group and S-101PT and references Issue #59. Close issue pending any further comment from originator (Dave).

**Comment by DavidGrant-NIWC** [comment]
Regardless of the outcome of #59, DCEG clause 3.9.1 para 2 needs to be updated or removed.
