### ISSUE TITLE
Attribute directional character

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#75]
I wonder if the naming for complex attribute **directional character** is suitable. 
In S-57 we have two options for encoding a directional light (CATLIT containing value 1: directional character): 

- Population of ORIENT OR 
- Population of SECTR/SECTR2. 

Due to the rules that apply (UOC, §12.8.6.5), only in very few cases, ORIENT is populated. Thus, after conversion to S-101, attribute orientation (and consequently complex attribute directional character) will very rarely be populated. 
My vision is that the attribute directional character will only be populated when the data producer will desire the bearing to the light to be displayed on the ECDIS.
The result is the vast majority of directional lights will not have S-101 **directional character** populated. This is not a major issue, but I find the name of the attribute and its associated guidance in the DCEG misleading.
The attribute seems to behave more as a portrayal one (except for sub-attribute moiré effect) than an encoding one, and so the attribute name a bit confusing.

Shouldn’t we rather call it **display light direction**?

**Comment by JeffWootton** [comment]
I do not think that this is an issue. As Christian correctly points out, the directional characteristic of a light or light sector can be encoded in two ways, which is encapsulated in the modelling of the complex attribute lightSector and the accompanying guidance. The ECDIS display will be dependent on how lightSector is populated - if the complex attribute directionalCharacter is populated then the display will be the transit indicated by the orientation attribute; and if the (narrow) sector limits are encoded the sector arc will be drawn.

**Comment by Christian-Shom** [comment]
Agree with Jeff's comment.
The only "issue" I see is just on the name of the attribute.

**Comment by JeffWootton** [comment]
**Discussion at S-101 DCEG Sub-Group 4 meeting:**

**Points to Note:**
-  Principle issue is the name of the attribute.

**Discussion/Decision:**
-  It was agreed that the attribute name directionalCharacter adequately describes the sub-attributes (moireEffect and orientation (for a transit)).

**Action:**
**-  Summarise discussion and close Issue (IHO Sec).**

No further discussion at S-101PT11. Close Issue.
