### ISSUE TITLE
Value of local magnetic anomaly

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#76]
Complex attribute **value of local magnetic anomaly** is mandatory in S-101 1.1.0 (multiplicity (1,2)).
In FR ENCs, we have cases where the value of the anomaly in unknown and INFORM is populated with something like "Local magnetic anomaly has been reported in this area."
I would thus be in favour of changing the multiplicity to (0,2) for **value of local magnetic anomaly**.
Another option would be to use a feature **Caution Area**, but I would prefer the previous option.
Happy to have your views on this.

**Comment by MikkoHovi-FI** [comment]
Isn't that case covered in DCEG (4.2.1, 4th bullet in Remarks) as follows:

> If the value of the local magnetic anomaly is unknown, a single instance of **value of local magnetic anomaly** must be encoded, with **magnetic anomaly value** populated with an empty (null) value and the complex attribute information containing textual **information** relevant to the local magnetic variation.

**Comment by Christian-Shom** [comment]
Thanks Mikko, you're perfectly right! 
I thus close the issue.
