### ISSUE TITLE
Action S-101PT9-18 - New Feature Mooring Buoy

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#81]
S-101PT10 Decision: S-101PT approved the removal of attribute categoryOfMooringWarpingFacility value _7_ (mooring buoy) as an allowable value and creation of a new MooringBuoy feature in S-101.

Action S-101PT10-18: IHO Sec to remove value _7_ (mooring buoy) as an allowable value for attribute categoryOfMooringWarpingFacility in S-101 and develop a new feature for mooring buoy.

Proposed new feature:

[Mooring Buoy.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/12320246/Mooring.Buoy.docx)

Model for the new MooringBuoy feature has been based on the models of other buoy features. In addition, please note:
- A new Boolean type attribute visitorsMooring has been included. This is intended to replace the attribute categoryOfSmallCraftFacility value _29_ (visitors mooring).
- In order to be able to use the already registered Hydrographic Dictionary term "Mooring Buoy" definition for the new feature, it is required to use the same name. This is not consistent with the convention for all other buoys and beacons in S-101 (BuoyXxxx and BeaconXxxx). There will be a proposal to the DCEG Sub-Group and S-101PT to amend all the names of buoy and beacon features in S-101 to standardise these names across all IHO Publications, similar to this proposal for MooringBuoy.

**Comment by KlasOstergren-SMA** [comment]
Agree to the proposal. Just one thought: Since many mooring buoys for yachts is made of plastic, will it then be relevant to add that to natureOfConstruction?
We don't encode any visitors mooring buoys so I havn't any strong opinion on this and hand it over to you all to decide if this is needed.

**Comment by JeffWootton** [comment]
**Discussion at S-101 DCEG Sub-Group 4 meeting:**

**Points to Note:**
-  Based on the modelling for existing S-101 buoy features, in particular the BuoyInstallation feature.
-  Note inclusion of new Boolean type attribute visitorsMooring (and corresponding removal of visitors mooring as an allowable value for attribute categoryOfSmallCraftFacility.
-  Note GitHub comment from Klas Östergren (SE) for attribute natureOfConstruction, which has now been added to the proposed new feature.

**Discussion/Decision:**
-  The modelling of the MooringBuoy feature was supported.
-  The inclusion of the visitorsMooring Boolean was supported.
-  Jeff Wootton (IHO Sec) highlighted the naming for this feature MooringBuoy, which is consistent with the term already included in the IHO GI Registry and the IHO Hydrograpgic Dictionary, but is inconsistent with the Buoy… naming convention that has been used for all existing buoy and beacon features in S-101. He suggested that a proposal should be made to the S-101PT to amend the names of all the buoys and beacons in S-101 to harminise them with other IHO publications, in particular the IHO Hydrographic Dictionary. There was concern raised that this will impact on other Product Specifications in S-100; and will significantly impact on Catalogues and portrayal rules.

**Action:**
**-  Report the endorsement of the draft DCEG Edition 1.2.0 amendments to the S-101PT (S-101PT11) for approval (IHO Sec).**
**-  Raise the issue of re-naming of buoys and beacons with the NIPWG and S-101PT for input to further discussions/actions.**

Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Papers S-101PT11-06.1 and S-101PT11-08.11, related decisions and Action S-101PT11-43. Changes applied for S-101 Edition 1.2.0 at DCEG clauses 2.3, 2.4.3, 2.5.9, 20.8 and 27.66. Edition 1.1.0 attribute categoryOfMooringWarpingFacility removed.

Close Issue.
