### ISSUE TITLE
Scale minimum and multiple Data coverage features

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#83]
I open this issue after Dave's and Hugh's comments (https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/52) on scale relations between DataCoverages and features.
At the 16th November meeting, it was agreed that within a dataset with multiple DataCoverage features, objects must not be split at the border between DataCoverages, and that all DataCoverages must be drawn as a unique dataset ("side by side"). It seems this decision is not in 1.1.0.
I see one (minor?) issue in terms of scale minimum calculation for individual features. Let's take figure 4-6 of the main document as an example:
 
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71139640/08720cdd-537c-4bb3-a49a-4b0870502ccb)

Features not being split means that:
- If the reference for scale minimum values is 22 000 (as stated in the DCEG 2.5.9, Note 5), then there will be no scale minimum policy applied on the objects within Data Coverages 1 and 2 until the MSVS reaches 29 999. This will result in screen clutter.
- If the reference for scale minimum values is 8 000, then object in Data Cooverage 3 will have 2 steps applied when MSVS is equal to its maximum display scale (22 000), which is a worse situation and surely to be avoided.

**Comment by DavidGrant-NIWC** [comment]
> I think the scenario in Fig 4.6 would indicate that separate datasets for Data coverages 1 and 2 should be produced, to avoid these issues where possible, the fig 4.6 does not promote best practice IMO.

Using separate datasets may cause some features to be obscured. Sector arcs / leg lines originating in the area of data coverage 3 will be obscured in the area of data coverage 1 and/or 2. In S-57 this is not the case provided the the data shares a common navigational purpose.

DataCoverages within a dataset will never obscure features originating in a different DataCoverage within the dataset.

**Comment by DavidGrant-NIWC** [comment]
In S-101 with route monitoring on it's likely that the ship would be using a MSVS of 22k as it approaches the port. If the area of DC1 & DC2 have a minimum display scale of 22k then they will be loaded/visible and will obscure information originating from DC3. Also note that DC1 & DC2 can be loaded in the case where the user zooms DC3 beyond its maximum display scale - DC3 will continue to display if there is no larger scale chart available.

In S-57 a navigational purpose can represent a seamless coverage of a geographic area (regardless of compilation scale). In S-101 multiple datasets form a seamless coverage only when they share a common _TBD_ [we currently use _minimumDisplayScale_ in our testbed].

**Comment by RichardCoyles** [comment]
Hi David, I have corrected my previous post, I agree most likely approaching at MSVS 22,000, but not that both dataCoverage areas will be displayed at MSVS 22,000. I would be interested @Christian-Shom views here - Richard

**Comment by DavidGrant-NIWC** [comment]
Both `DataCoverage` areas will be displayed as a result of applying the data loading algorithm specified in S-101 PS 1.1.0 Annex D.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/9441d14b-5d63-49c5-9864-778bdfb0c8ce)

A `MSVS` of 1:22k is assigned to scale band 10. The datasets will be assigned to scale bands as follows:

|Dataset|_maximumDisplayScale_|_minimumDisplayScale_|Scale Bands|
|:---:|:---:|:---:|:---:|
|1|8k|22k|10, 11
|2|8k|22k|10, 11
|3|22k|45k|9

Datasets 1 and 2 will be loaded (assuming they intersect the screen) because they contain the scale band assigned to the MSVS. Dataset 3 will be loaded if datasets from scale band 10 don't cover the screen.

**Comment by alvarosanuy** [comment]
I think the conversation has shifted from discussing ECDIS display performance among different data coverages within a dataset to looking at the different data coverages as if they were <> cells. All DataCoverages in one dataset have to be loaded at the same time and their content will display based on MSVS and SCAMIN.
I think the concerns are around DataCoverages being unique datasets and how they would display/interact at <> MSVS (??)
To be honest, there are a number of issues currently open around loading/unloading; ENC content display, SCAMIN behaviour and overscale. 
**I would strongly recommend we make time and workshop all this (around a big whiteboard) at the upcoming S101PT11 meeting.
Theory vs current statements in the different S101/S98 documents vs implementation limitations at the OEM level.**

@TomRichardson6 - something to consider for the S101PT11 meting Agenda??

**Comment by Christian-Shom** [comment]
> Hi David, I have corrected my previous post, I agree most likely approaching at MSVS 22,000, but not that both dataCoverage areas will be displayed at MSVS 22,000. I would be interested @Christian-Shom views here - Richard

Agree with Richard that when MSVS=22000, only DC3 must be displayed. DC1 and 2 have an effective MinDS=21999.
This is something that we must make clear in the PS.

**Comment by TDYCARHugh** [comment]
A note about graphical data being obscured, such as light sectors or Text, by a larger scale dataset. Consider the following:
Determine datasets to be displayed (set of datasets that overlap the viewing window)
Draw one priority (lowest to highest) at a time for all the chosen datasets drawing the larger scale datasets last for each priority.  
For minor overlaps on skin of the earth, the larger scale will be on top.
Text, light sectors etc will not be obscured except by other text/light sectors etc.

**Comment by DavidGrant-NIWC** [comment]
> Agree with Richard that when MSVS=22000, only DC3 must be displayed. DC1 and 2 have an effective MinDS=21999.
This is something that we must make clear in the PS.

The three data coverages are all displayed anytime any one of them is displayed:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/2f4025c3-3503-41ac-b4a8-7228f9cac317)

> Coming back to the topic of this issue, we already have the answer in clause2.5.9 of the DCEG:
![image](https://user-images.githubusercontent.com/71139640/266018096-d345cea5-54c4-4b28-a930-b00079905f92.png)
I don't think this should be repeated in the main document as this is purely data encoding.

Since this seems to resolve the original issue, recommend close this issue.

**Comment by Christian-Shom** [comment]
> The three data coverages are all displayed anytime any one of them is displayed:

Agree (there has been some confusion between the 2 situations).

> Since this seems to resolve the original issue, recommend close this issue.

Agree if Sub-Group approves.

**Comment by JeffWootton** [comment]
Refer to Paper S-101PT11-06.5 and related decisions, related decisions and Action S-101PT11-24. Change applied for S-101 Edition 1.2.0 at DCEG clause 2.5.9.

Close Issue.
