### ISSUE TITLE
Action S-101PT10-17 - Encoding of mooring cables

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#84]
S-101PT10 Decision: S-101PT agreed that further investigation was required to determine the best option for the modelling of the attribute categoryOfMooringWarpingFacility value _6_ (mooring cable).

Action S-101PT10-17: IHO Sec develop a proposal on options for the modelling of mooring cables for consideration of the DCEG Sub-Group.

The only distinction in the S-101 DCEG for encoding mooring cables using values categoryOfCable = _6_ (mooring cable) and categoryOfMooringWarpingFacility = _6_ (mooring cable) is related to the encoding of mooring trots:

![Mooring Trots](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/d3077d74-d393-4866-82d4-058b8d4e024c)

Given that this is the only distinction in the DCEG, suggest that categoryOfMooringWarpingFacility = _6_ is removed as an allowable value in S-101. On the assumption that the junction cables should be identified as their own cable type, suggest that a new value categoryOfCable = _7_ (junction cable) is introduced for CableSubmarine:

![categoryOfCable](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/ad354473-8f5d-4838-9279-62daf3afb7a4)

**Comment by alvarosanuy** [comment]
Makes sense to me.
