### ISSUE TITLE
Compilation scale (CS) and maximum display scale (MaxDS)

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#87]
After various internal and external discussions, Shom is of the opinion that the MaxDS of a Data Coverage should be set to the CS of data. This is in line with MaxDS being the starting point for the calculation of scale minimum (in the case of Dataset with a unique Data Coverage feature).
This is an important point for the data producers to elaborate their S-101 ENC portfolio and I suggest adding the following sentence in clause 4.5.3 (Data Coverage rules) of the main document:
"_The **maximum display scale** of a **Data Coverage** feature should be the compilation scale of data for this **Data Coverage**. It is also the default viewing scale of the **Data Coverage** on the ECDIS and the reference for the calculation of **scale minimum** values when a dataset contains a unique **Data Coverage** feature._"

**Comment by DavidGrant-NIWC** [comment]
This begs the question of why `optimumDisplayScale` is not being used in S-101. Why use `maximumDisplayScale` to indicate both the maximum and compilation/optimum scale of the data?
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/4ef503b6-dfda-4b9c-99a8-6720574a640a)

**Comment by Christian-Shom** [comment]
HOs have been used to work with S-57 UOC which states: 
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71139640/270af39b-7bf2-4346-9850-97fdbe7c7d03)
This is why I don't think adding Optimum DS in S-101 is a good idea. However, if this is necessary for implementation, why not writing somewhere in 4.7 that for S-101 Datasets, OptimumDS=MaximumDS?

**Comment by Christian-Shom** [comment]
Feedback from Mikus:
I think we need to keep the already complex things simple and somehow clarify that Optimum display scale for the ECDIS and Navigation purpose should not be used or considered. 
Hence, MaxDS=where the compilers compile the data as a reference scale for the "data column" MaxDS to MinDS. 
I think this statement would help every HO and every ECDIS implementer and tester.

**Comment by LizHahessy** [comment]
I agree with Dave's suggestion on the use of optimumDisplayScale.

**Comment by benhazelgrove** [comment]
After multiple discussions internally at AHO, we believe that MaxDS should be a value that is equal to compilation scale of data. Allowing the Mariner to zoom past the intended viewing scale without an overscale pattern is not what our products were developed for. The error of positioning is multiplied, and it's not something we are comfortable with allowing.
If any example of this was to be used in our case, we would only see a use case for the largest scale product in our portfolio. (Port cell for example)

Using both MaxDs and OptimumDS is not required for our portfolio. We envisage that we will populate MaxDS (matching S-57 comp scale) and MinDS (matching the next smaller scale product MaxDS in our gridded scheme). AHO can use this approach as we have used the attribute SCAMIN to identify features and display them at a scale where we believe they should appear. Our overlapping S-57 products have consistent SCAMIN values for corresponding features in each product.

This discussion leads to the loading/display issues we are seeing, where MinDS is used to display a DataCoverage until +1, whereas we would like it to use MinDS -1.

**Comment by JeffWootton** [comment]
Refer to Paper S-101PT11-06.5, related decisions and Action S-101PT11-21. Changes applied for S-101 Edition 1.2.0 throughout both S-101 Main document and DCEG in accordance with Action.  New Issue to be opened for feedback on implementation and testing.

Close Issue.
