### ISSUE TITLE
Figure 4-6 in the Main document

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#88]
Although figures have been improved, I find figure 4-6 in the main document a bit confusing as it suggests that Data Coverage 3 is not displayed when the MSVS is larger than 22 000.
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71139640/e943e8c9-154f-4113-8e5c-821600d8d102)
I suggest reviewing the figure and possibly turning it upside down to have the larger scale at the bottom.
Happy  to hear about other things that can be improved.

**Comment by Christian-Shom** [comment]
To sum-up for the 2023_09_07 Sub-Group meeting, suggest reviewing figure 4-6 as follows:

- Turn it upside down (idem for figure 4-5 for consistency);
- Make it obvious that the 3 Data Coverages (DC) will be drawn at once;
- "link" the chart images to the MaxDS of each DC;
- If possible (may be difficult), show prison bars on DC3 when MSVS>22 000.

**Comment by Christian-Shom** [comment]
Following the discussion at the 2023_09_07 Sub-Group meeting, the figures will be reviewed for edition 1.2.0.
A more logical use case will be used for figure 4-6 (for the situation currently shown, 3 different datasets should be created).

**Comment by Christian-Shom** [comment]
Here is an initial proposal for the improvement of figure 4-5. Do not hesitate to comment.
![Figure_4_5](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71139640/113d9cca-1495-4064-9426-6ba51abfe382)

**Comment by DavidGrant-NIWC** [comment]
Figure 4-5 is intended to show multiple datasets. Figure 4-6 is intended to show the use of multiple data coverage features within a dataset.

**Comment by Christian-Shom** [comment]
> Figure 4-5 is intended to show multiple datasets. Figure 4-6 is intended to show the use of multiple data coverage features within a dataset.

Agree. The figure is for 4-5 and would be a model as a base for 4-6.

**Comment by HolgerBothien** [comment]
I would turn it upside down, intentionally one would look from above and then the large scale data should be on top.
Though the drawing order is vice versa.

**Comment by JeffWootton** [comment]
Refer to  Paper S-101PT11-06.5, related decisions and Action S-101PT11-22. Changes applied for S-101 Edition 1.2.0 accordingly.

Close Issue.
