### ISSUE TITLE
Iso8211 Encoding : CurveRecord in an Update DataSet

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Documentation-and-FC#89]
In the definition of a curve record in Update Dataset Structure, the CI2L is mandatory under a segment header (see below) 
![Capture d’écran de 2023-09-09 09-12-48](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/24851994/eeb22b24-a5fc-4aac-b123-889327adb383)
Question : When the COCC control field is for a deletion of a number of coordinates (eg Instruction=2,Index=3,Number=4), what must be the content of the CI2L ? => (eg The 4 coordinates to be deleted ?)

**Comment by kusala9** [comment]
Needs correction at S100WG?

**Comment by kusala9** [comment]
ah, if it is 0..* at the S-100 level that's ok. Yes, you're right a product spec can restrict values if it wants to but, as you pointed out, that's probably incorrect here. I was at S-101PT last week with Tom de Puyt and we spent some time discussing the problems they (and we!) had with composite curves. I think they want to explain the situation in S-100 a bit clearer as NIWC also had some confusion on how the CUCO is used in composite curves. I wondered if this would be a clarification too but I guess not. I think ESRI will do a paper next week for the meeting....

**Comment by plebihan29n** [comment]
I take the opportunity of this discussion about update curve record to get advice (or confirmation) :

In the S-164 "Loading of New Update" , to update a curve (delete points and insert new points) , I have generated the following sequence in the **same record** : 
<CurveRecord>
            <Identifier rcid="624" rcnm="120" ruin="modify" version="2"/>
            <Segment intp="loxodromic">
                
                <COCC index="2" number="191" ruin="delete"/>
                
                <COCC index="1" number="202" ruin="insert"/>
                <Coordinate2D>(-32.54306012,60.9246682)(-32.54265416,60.9250878).....</Coordinate2D>
            </Segment>
</CurveRecord>     

I just realize that this sequence is not conform as I use twice the "COCC" field.
I understand that I have to generate two records (one for deletion, one for insertion), you confirm ?

For information , I use this sequence (delete + insert) to respect the original S57 sequence from S-64 test datasets.

A better way to do this is to use the "modify" instruction as :

<Segment intp="loxodromic">
                
                <COCC index="2" number="191" ruin="modify"/>
                <Coordinate2D>(-32.54306012,60.9246682)(-32.54265416,60.9250878).....</Coordinate2D>
</Segment>
are you also agree with this "modify" sequence ?

**Comment by mikan66** [comment]
In my opinion "modify" is perfectly acceptable when this is the situation and easier to indicate to the user.  Doing a "delete" then "insert" to simulate a "modify" operation seems strange, but maybe there is some S-57 historical reason for this that I don't have.

**Comment by plebihan29n** [comment]
I agree Mikan : it is more efficient to modify or to insert the new points in the same step. (same record)

Anyway, sorry to have introduce this new point as I guess that this point deserve a separate new issue in test datasets repository.
In turn I propose to go one discussion on  https://github.com/iho-ohi/S-101-Test-Datasets/issues/70

And as soon as the correction will be done on the S101 documentation on 'curve record structure'  for ER , I propose to close this current issue.

**Comment by HolgerBothien** [comment]
> ah, if it is 0..* at the S-100 level that's ok. Yes, you're right a product spec can restrict values if it wants to but, as you pointed out, that's probably incorrect here. I was at S-101PT last week with Tom de Puyt and we spent some time discussing the problems they (and we!) had with composite curves. I think they want to explain the situation in S-100 a bit clearer as NIWC also had some confusion on how the CUCO is used in composite curves. I wondered if this would be a clarification too but I guess not. I think ESRI will do a paper next week for the meeting....

This issue here is not about composite curves,, and if the issue is in S-100 it is the wrong repository too. :-) 
But I am happy to assist as long as the paper is available.

**Comment by HolgerBothien** [comment]
@plebihan29n 
I have seen that you had some questions:

Yes, COCC is only allowed once for each segment (which means for each curve record since we have always one segment for a curve in S-101)
Your example regarding the use of modify is only partly correct.
Original: Delete **191** coordinates and then Insert **202** coordinates
Your proposal: Modify **191** coordinates
Correct proposal: Modify **191** coordinates + Insert **11** coordinates after the last modified coordinate
From an efficiency point of view there will be not much difference between the Delete + Insert and the Modify + Insert apporach, since in both cases two records are required and all 202 coordinates must be stored.
I don't know how many coordinates the original curve has but modification of all or close to all is not more efficient than delete and insert.
Another option (and now it becomes really weird): delete the segment and insert another segment. (SECC field)

**Comment by plebihan29n** [comment]
Thanks Holger.
Yes you are right , my proposal is a bad and too quick "copy/paste".
For the moment I stay with "insert and delete" in two separate records. and If time i will propose a second way as you propose : modify and insert ("Insert" I think is enough in this case as the other 191 coordinates doesn't change))

About SECC , it is new for me I have to learn how to use

**Comment by kusala9** [comment]
what would be really good is to get representative examples of both models in some updates for the S-164 test datasets... For a long time some implementations just do delete-insert where it is more efficient to do a modify (and vice versa) so it would be great if we can get good examples of both into the S-164. SECC too - if we can, some simple examples embedded in an update would strengthen the test datasets significantly. I like the xml encoding of the records, at least then you can hardwire in the behaviour you want... Jonathan.

**Comment by JeffWootton** [comment]
In regard to the original intent of this Issue, it appears that the consensus is to amend the cardinality of the C2IL field from [1..*] to [0..*]. There is no impediment in S-100 to make this change.

The change will be made for the draft S-101 Main document Edition 2.0.0 for approval at the S-101PT13 meeting (June 2024), after which this Issue will be closed.

**Comment by mikan66** [comment]
We have an open issues to test this in our Testbed.  In general, updating of S-101 datasets is largely untested as we head towards 2.0.  There are subtle differences in how updating is done in S-101 compared to S-57.  Fully testing all aspects of S-101 updating with known scenarios needs to be addressed to shake out any issues (production side, and ECDIS/OEM side).  My concerns are more on the mechanism of updating vs enhanced portrayal via Feature Update Information, (although tying the two together also needs more testing, mechanism + UpdateInformation).

**Comment by JeffWootton** [comment]
Change approved at S-101PT13. Close issue.
