### ISSUE TITLE
Iso8211 Encoding : CompositeCurveRecord in a base structure dataset

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Documentation-and-FC#90]
In the definition of a Composite Curve, the number of Curve Component Fields could be 0 => see below
![Capture d’écran de 2023-09-09 09-30-03](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/24851994/4481c624-2bb0-4638-8879-858f1c715f7c)
This number , Must be at least one ?

**Comment by HolgerBothien** [comment]
Yes, when the composite curve is inserted, which is true in a base dataset. In an update the number may be 0 since the update may only change the associations to information types. Nevertheless, if RVER=1 it must be 1 again. This is outside of the scope of this diagram but can be a validation test.

**Comment by JeffWootton** [comment]
In regard to the original intent of this Issue, it appears that the consensus is to amend the cardinality of the COCO field from `[0..*]` to `[1..*]`.

The change will be made for the draft S-101 Main document Edition 2.0.0 for approval at the S-101PT13 meeting (June 2024), after which this Issue will be closed.

PLEASE NOTE: This change has only been applied to the Base Dataset structure (Main document clause B-5). Based on Holger's comment, the corresponding change is not required for the composite curve record for the Update Dataset structure (clause B-6).

**Comment by JeffWootton** [comment]
Change approved at S-101PT13. Close Issue.
