### ISSUE TITLE
Eliminate ambiguity when evaluating / encoding vertically overlapping QoBD features.

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#91]
The current guidance in the DCEG has the potential to create a discontinuity at the minimum value of the topmost QoBD feature. Most of the QoBD features must satisfy DRVAL1 < safety contour <= DRVAL2, but the topmost QoBD feature must satisfy DRVAL1 <= safety contour <= DRVAL2. To eliminate this discontinuity, suggest:

- [ ] Clarify that DRVAL1 is disallowed (must be null) on the topmost QoBD feature for a given date range.
- [ ] Clarify that DRVAL2 is disallowed (must be null) on the bottommost QoBD feature for a given date range.
- [ ] Highlight the inclusive / exclusive properties of DRVAL1 and DRVAL2 so that it’s clear for all encoders which QoBD feature applies at the vertical boundary between two features:
  * Feature is applicable when the date range is active and [(DRVAL1 is null) or (DRVAL1 < safety contour)] and [(DRVAL2 is null) or (safety contour <= DRVAL2)] (modify this equation as appropriate).

See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/127 for prior discussion within the PSWG.

**Comment by alvarosanuy** [comment]
@JeffWootton - Has this recommendation been included in DCEG 1.2.0?

**Comment by JeffWootton** [comment]
Amendments applied to clause 3.8.1 on 09/11/23.
