### ISSUE TITLE
PS:  Recommend add clause describing vertical CRS for `VerticalDatumOfData`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#93]
Clause 5.3 describes "Vertical CRS for Soundings", but there is no equivalent description of the vertical CRS for the vertical datum. Recommend add description or modify title of 5.3 and describe differences.

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/59e0236d-95cc-4dfe-b3cc-993030b63096)

**Comment by JeffWootton** [comment]
[@HolgerBothien](https://github.com/HolgerBothien): Please advise a resolution to this Issue (refer also to Issue #92). Thanks.

**Comment by JeffWootton** [comment]
Have included the following clarification to the S-101 Main document:

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70211773/20fbb556-b952-4db3-ae0a-5fce50b6d8dc)

For discussion at S-101PT13, after which this Issue will be closed.

**Comment by JeffWootton** [comment]
Decision from S-101PT13: Draft change approved with some refinement made during teh meeting.

Close Issue.
