### ISSUE TITLE
Attribute "linkage"

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-101-Documentation-and-FC#97]
The attribute _linkage_, currently of type _text_, should be restricted to URL type, or at least URI (ref. S-100 1-4.6).  _Linkage_ is defined in DCEG 1.2.0 (20231016) clause 27.121 as the _Location (address) for online access using a URL/URI address or similar addressing scheme._

- The _text_ type is inconsistent with the intent of the definition.
- URLs can be accessed (assuming it actually exists, has the right permissions, etc.) with an ordinary web browser; some URI formats like doi: identifiers can also be so accessed. Plain text, on the other hand permits any string.

**Comment by rmalyankar** [comment]
I just noticed that the Simple attribute types clause (2.4.2) in the DCEG 1.2.0 does not include URL (nor URI or URN), is this intentional? Apart from _linkage_, when maritime resource names are introduced into S-101 the relevant attribute should be of type URN.

(The GI Registry allows _URN_ as a data type and I expect it allows _URL_ and _URI_ too.)

**Comment by TomRichardson6** [comment]
Support this change.

**Comment by JeffWootton** [comment]
Support this change, however need to determine whether the type should be URL or URI?

**Comment by rmalyankar** [comment]
A URL, one way or another (see below). Everybody knows to access a URL with the HTTP or HTTPS protocol, but a URI also allows URNs and there would have to be conventions defined as to what forms of URNs are acceptable and how to access the resources they identify, which may be an unnecessary elaboration at this point of time.

So either:

- Change the type from _text_ to _URI_ in the registry, which would be 100% consistent with the current registry definition, and in the product specification add a constraint restricting it to URIs which are also https or http URLs (i.e., it must begin with http:// or https://, which is enforceable with _textPattern_).
- Change the type in the registry from _text_ to _URL_ (which makes the type in S-101 also _URL_) and amend the defintion in the registry accordingly. As an amendment to the original intent of _linkage_ this would have to be cleared with other interested parties e.g. NIPWG.

Note that:
1. URL is a derived type from URI (S-100  1-4.6).
2. The definition of _linkage_ in the GI Registry is "_Location (address) for online access using a URL/URI address or similar addressing scheme._"
3. While the official URL format also allows relative URLs (which don't begin with http or https), going into that seems another unnecessary elaboration at this point.

**Comment by rmalyankar** [comment]
Noe also that for security reasons it may well be that access to Web sites outside the "ECDIS firewall" (assuming there is one) or off the ECDIS/INS computer ends up being blocked for security considerations. That is in fact what I would do, or at least carefully control which sites can be accessed through the firewall. So the linkage might be an active link only on systems not subject to this (hypothetical) ECDIS security rule.

**Comment by rmalyankar** [comment]
The S-101 DCEG uses _online resource_ (which contains _linkage_) in only one place, the information type _ContactDetails_, where it would normally be the web site of an organization. That reinforces my suggestion to limit it to URLs. Recommend the first option I mentioned earlier:

> Change the type from text to URI in the registry, which would be 100% consistent with the current registry definition, and in the product specification add a constraint restricting it to https or http URLs (i.e., it must begin with http:// or https://, which is enforceable with textPattern).

The textPattern should be added in the S-101 feature catalogue.

**Comment by JeffWootton** [comment]
S-101PT12 Decision: Apply change as recommended in paper S-101PT12-05.1.1 (for S-101 Edition 1.3.0 draft). Decision was to include URI as the new attribute type.

Change applied 07 march 2024. Close issue.
